const airportsData = [
    {
        iata: "DXB",
        city: "Dubai",
        country: "United Arab Emirates",
        terminal: "Terminal 2",
        timezone: "Asia/Dubai",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "DWC: 60 km | SHJ: 25 km",
        phone: "+971 4 224 5555",
        website: "https://www.dubaiairports.ae",
        locationUrl: "https://goo.gl/maps/8Q3Q5"
    },
    {
        iata: "ABH",
        city: "Abha",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "18 km to City Center",
        nearbyAirports: "None",
        phone: "+966 17 224 6011",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/abh"
    },
    {
        iata: "ADD",
        city: "Addis Ababa",
        country: "Ethiopia",
        terminal: "Terminal 2",
        timezone: "Africa/Addis_Ababa",
        distanceCenter: "6 km to Bole",
        nearbyAirports: "None",
        phone: "+251 11 665 0400",
        website: "https://addisairport.com",
        locationUrl: "https://goo.gl/maps/add"
    },
    {
        iata: "AER",
        city: "Sochi",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Europe/Moscow",
        distanceCenter: "28 km to City Center",
        nearbyAirports: "None",
        phone: "+7 800 301 19 91",
        website: "https://aer.aero",
        locationUrl: "https://goo.gl/maps/aer"
    },
    {
        iata: "AHB",
        city: "Abha",
        country: "Saudi Arabia",
        terminal: "International Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "20 km to City Center",
        nearbyAirports: "None",
        phone: "+966 7 224 6011",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/ahb"
    },
    {
        iata: "AJF",
        city: "Al-Jawf",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "25 km to Sakaka",
        nearbyAirports: "None",
        phone: "+966 14 624 2222",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/ajf"
    },
    {
        iata: "ALA",
        city: "Almaty",
        country: "Kazakhstan",
        terminal: "International Terminal",
        timezone: "Asia/Almaty",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+7 727 270 3333",
        website: "https://alaport.com",
        locationUrl: "https://goo.gl/maps/ala"
    },
    {
        iata: "AMD",
        city: "Ahmedabad",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "9 km to City Center",
        nearbyAirports: "None",
        phone: "+91 79 2286 9211",
        website: "https://www.svpia.com",
        locationUrl: "https://goo.gl/maps/amd"
    },
    {
        iata: "AMM",
        city: "Amman",
        country: "Jordan",
        terminal: "Terminal 1",
        timezone: "Asia/Amman",
        distanceCenter: "30 km to Downtown",
        nearbyAirports: "ADJ (Civil Only)",
        phone: "+962 6 401 0250",
        website: "https://qaiairport.com",
        locationUrl: "https://goo.gl/maps/amm"
    },
    {
        iata: "AQI",
        city: "Al Qaisumah",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "20 km to Hafr Al Batin",
        nearbyAirports: "None",
        phone: "+966 13 722 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/aqi"
    },
    {
        iata: "ASB",
        city: "Ashgabat",
        country: "Turkmenistan",
        terminal: "Main Terminal",
        timezone: "Asia/Ashgabat",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+993 12 23 20 34",
        website: "https://ashgabatairport.gov.tm",
        locationUrl: "https://goo.gl/maps/asb"
    },
    {
        iata: "ASM",
        city: "Asmara",
        country: "Eritrea",
        terminal: "Main Terminal",
        timezone: "Africa/Asmara",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+291 1 181 822",
        website: "https://asmara-airport.com",
        locationUrl: "https://goo.gl/maps/asm"
    },
    {
        iata: "AYT",
        city: "Antalya",
        country: "Turkey",
        terminal: "Terminal 1",
        timezone: "Europe/Istanbul",
        distanceCenter: "13 km to City Center",
        nearbyAirports: "None",
        phone: "+90 242 330 30 30",
        website: "https://www.antalya-airport.aero",
        locationUrl: "https://goo.gl/maps/ayt"
    },
    {
        iata: "BAH",
        city: "Manama",
        country: "Bahrain",
        terminal: "Main Terminal",
        timezone: "Asia/Bahrain",
        distanceCenter: "7 km to Souq",
        nearbyAirports: "DMM: 85 km",
        phone: "+973 1733 9339",
        website: "https://www.bahrainairport.bh",
        locationUrl: "https://goo.gl/maps/bah"
    },
    {
        iata: "BEG",
        city: "Belgrade",
        country: "Serbia",
        terminal: "Terminal 2",
        timezone: "Europe/Belgrade",
        distanceCenter: "18 km to City Center",
        nearbyAirports: "None",
        phone: "+381 11 209 4000",
        website: "https://beg.aero",
        locationUrl: "https://goo.gl/maps/beg"
    },
    {
        iata: "BEY",
        city: "Beirut",
        country: "Lebanon",
        terminal: "Main Terminal",
        timezone: "Asia/Beirut",
        distanceCenter: "9 km to Downtown",
        nearbyAirports: "None",
        phone: "+961 1 628 000",
        website: "http://www.beirutairport.gov.lb",
        locationUrl: "https://goo.gl/maps/bey"
    },
    {
        iata: "BGW",
        city: "Baghdad",
        country: "Iraq",
        terminal: "Babylon Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "16 km to Green Zone",
        nearbyAirports: "None",
        phone: "+964 0790 140 3537",
        website: "http://baghdadairport.info",
        locationUrl: "https://goo.gl/maps/bgw"
    },
    {
        iata: "BGY",
        city: "Milan",
        country: "Italy",
        terminal: "Bergamo Orio al Serio",
        timezone: "Europe/Rome",
        distanceCenter: "45 km to Milan",
        nearbyAirports: "MXP: 90km | LIN: 50km",
        phone: "+39 035 326323",
        website: "https://www.milanbergamoairport.it",
        locationUrl: "https://goo.gl/maps/bgy"
    },
    {
        iata: "BJV",
        city: "Bodrum",
        country: "Turkey",
        terminal: "International Terminal",
        timezone: "Europe/Istanbul",
        distanceCenter: "36 km to Bodrum City",
        nearbyAirports: "DLM: 200 km",
        phone: "+90 252 523 01 01",
        website: "http://www.milas-bodrumairport.com",
        locationUrl: "https://goo.gl/maps/bjv"
    },
    {
        iata: "BND",
        city: "Bandar Abbas",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "Qeshm (GSM): 30 km (Ferry)",
        phone: "+98 76 3361 1011",
        website: "https://bandarabbas.airport.ir",
        locationUrl: "https://goo.gl/maps/bnd"
    },
    {
        iata: "BSZ",
        city: "Bishkek",
        country: "Kyrgyzstan",
        terminal: "Manas Intl",
        timezone: "Asia/Bishkek",
        distanceCenter: "25 km to City Center",
        nearbyAirports: "None",
        phone: "+996 312 693 109",
        website: "http://www.airport.kg",
        locationUrl: "https://goo.gl/maps/bsz"
    },
    {
        iata: "BUD",
        city: "Budapest",
        country: "Hungary",
        terminal: "Terminal 2B",
        timezone: "Europe/Budapest",
        distanceCenter: "16 km to City Center",
        nearbyAirports: "None",
        phone: "+36 1 296 7000",
        website: "https://www.bud.hu",
        locationUrl: "https://goo.gl/maps/bud"
    },
    {
        iata: "CCJ",
        city: "Kozhikode",
        country: "India",
        terminal: "International Terminal",
        timezone: "Asia/Kolkata",
        distanceCenter: "28 km to City Center",
        nearbyAirports: "COK: 160 km",
        phone: "+91 483 271 2630",
        website: "https://www.aai.aero",
        locationUrl: "https://goo.gl/maps/ccj"
    },
    {
        iata: "CCU",
        city: "Kolkata",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "None",
        phone: "+91 33 2511 8036",
        website: "https://www.aai.aero",
        locationUrl: "https://goo.gl/maps/ccu"
    },
    {
        iata: "CFU",
        city: "Corfu",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "2 km to Corfu Town",
        nearbyAirports: "None",
        phone: "+30 2661 089600",
        website: "https://www.cfu-airport.gr",
        locationUrl: "https://goo.gl/maps/cfu"
    },
    {
        iata: "CIT",
        city: "Shymkent",
        country: "Kazakhstan",
        terminal: "Main Terminal",
        timezone: "Asia/Almaty",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "Tashkent (TAS): 120 km",
        phone: "+7 7252 45 50 30",
        website: "http://airserver.kz",
        locationUrl: "https://goo.gl/maps/cit"
    },
    {
        iata: "CMB",
        city: "Colombo",
        country: "Sri Lanka",
        terminal: "Bandaranaike Intl",
        timezone: "Asia/Colombo",
        distanceCenter: "30 km to City Center",
        nearbyAirports: "None",
        phone: "+94 11 225 2861",
        website: "https://www.airport.lk",
        locationUrl: "https://goo.gl/maps/cmb"
    },
    {
        iata: "COK",
        city: "Kochi",
        country: "India",
        terminal: "Terminal 3",
        timezone: "Asia/Kolkata",
        distanceCenter: "25 km to City Center",
        nearbyAirports: "None",
        phone: "+91 484 261 0115",
        website: "https://cial.aero",
        locationUrl: "https://goo.gl/maps/cok"
    },
    {
        iata: "CTA",
        city: "Catania",
        country: "Italy",
        terminal: "Terminal A",
        timezone: "Europe/Rome",
        distanceCenter: "4 km to City Center",
        nearbyAirports: "PMO: 240 km",
        phone: "+39 095 723 9111",
        website: "https://www.aeroporto.catania.it",
        locationUrl: "https://goo.gl/maps/cta"
    },
    {
        iata: "DAC",
        city: "Dhaka",
        country: "Bangladesh",
        terminal: "Terminal 2",
        timezone: "Asia/Dhaka",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "None",
        phone: "+880 2 7911042",
        website: "http://caab.gov.bd",
        locationUrl: "https://goo.gl/maps/dac"
    },
    {
        iata: "DAR",
        city: "Dar es Salaam",
        country: "Tanzania",
        terminal: "Terminal 3",
        timezone: "Africa/Dar_es_Salaam",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "ZNZ: 70 km (Ferry)",
        phone: "+255 22 284 4371",
        website: "https://taa.go.tz",
        locationUrl: "https://goo.gl/maps/dar"
    },
    {
        iata: "DBB",
        city: "Al Alamein",
        country: "Egypt",
        terminal: "Main Terminal",
        timezone: "Africa/Cairo",
        distanceCenter: "30 km to Marina El Alamein",
        nearbyAirports: "HBE: 100 km",
        phone: "+20 46 410 0000",
        website: "http://eac-airports.com",
        locationUrl: "https://goo.gl/maps/dbb"
    },
    {
        iata: "DBV",
        city: "Dubrovnik",
        country: "Croatia",
        terminal: "Main Terminal",
        timezone: "Europe/Zagreb",
        distanceCenter: "15 km to Old Town",
        nearbyAirports: "TIV: 50 km",
        phone: "+385 20 773 100",
        website: "https://www.airport-dubrovnik.hr",
        locationUrl: "https://goo.gl/maps/dbv"
    },
    {
        iata: "DEL",
        city: "Delhi",
        country: "India",
        terminal: "Terminal 3",
        timezone: "Asia/Kolkata",
        distanceCenter: "16 km to New Delhi",
        nearbyAirports: "None",
        phone: "+91 124 3376000",
        website: "https://www.newdelhiairport.in",
        locationUrl: "https://goo.gl/maps/del"
    },
    {
        iata: "DMM",
        city: "Dammam",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "30 km to City Center",
        nearbyAirports: "BAH: 85 km",
        phone: "+966 13 883 4444",
        website: "https://kfia.gov.sa",
        locationUrl: "https://goo.gl/maps/dmm"
    },
    {
        iata: "DOH",
        city: "Doha",
        country: "Qatar",
        terminal: "Hamad International",
        timezone: "Asia/Qatar",
        distanceCenter: "15 km to Souq Waqif",
        nearbyAirports: "None",
        phone: "+974 4010 6666",
        website: "https://dohahamadairport.com",
        locationUrl: "https://goo.gl/maps/doh"
    },
    {
        iata: "DYU",
        city: "Dushanbe",
        country: "Tajikistan",
        terminal: "Main Terminal",
        timezone: "Asia/Dushanbe",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "None",
        phone: "+992 47 449 4233",
        website: "http://airport.tj",
        locationUrl: "https://goo.gl/maps/dyu"
    },
    {
        iata: "EAM",
        city: "Najran",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "26 km to City Center",
        nearbyAirports: "None",
        phone: "+966 7 544 0444",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/eam"
    },
    {
        iata: "EBB",
        city: "Entebbe",
        country: "Uganda",
        terminal: "Main Terminal",
        timezone: "Africa/Kampala",
        distanceCenter: "40 km to Kampala",
        nearbyAirports: "None",
        phone: "+256 31 235 2000",
        website: "https://caa.go.ug",
        locationUrl: "https://goo.gl/maps/ebb"
    },
    {
        iata: "EBL",
        city: "Erbil",
        country: "Iraq",
        terminal: "International Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "7 km to Citadel",
        nearbyAirports: "ISU: 170 km",
        phone: "+964 66 281 0000",
        website: "https://erbilairport.com",
        locationUrl: "https://goo.gl/maps/ebl"
    },
    {
        iata: "ELQ",
        city: "Gassim",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "25 km to Buraydah",
        nearbyAirports: "None",
        phone: "+966 6 380 0055",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/elq"
    },
    {
        iata: "ESB",
        city: "Ankara",
        country: "Turkey",
        terminal: "International Terminal",
        timezone: "Europe/Istanbul",
        distanceCenter: "28 km to City Center",
        nearbyAirports: "None",
        phone: "+90 312 398 00 00",
        website: "https://www.esenbogaairport.com",
        locationUrl: "https://goo.gl/maps/esb"
    },
    {
        iata: "EVN",
        city: "Yerevan",
        country: "Armenia",
        terminal: "Zvartnots Intl",
        timezone: "Asia/Yerevan",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "None",
        phone: "+374 10 493 000",
        website: "http://www.zvartnots.aero",
        locationUrl: "https://goo.gl/maps/evn"
    },
    {
        iata: "GIZ",
        city: "Jizan",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "3 km to City Center",
        nearbyAirports: "ABH: 200 km",
        phone: "+966 7 322 2222",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/giz"
    },
    {
        iata: "GSM",
        city: "Qeshm Island",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "50 km to Qeshm City",
        nearbyAirports: "BND: Ferry access",
        phone: "+98 76 3533 5040",
        website: "http://qeshmairport.ir",
        locationUrl: "https://goo.gl/maps/gsm"
    },
    {
        iata: "GYD",
        city: "Baku",
        country: "Azerbaijan",
        terminal: "Terminal 1",
        timezone: "Asia/Baku",
        distanceCenter: "25 km to City Center",
        nearbyAirports: "None",
        phone: "+994 12 497 27 27",
        website: "https://airport.az",
        locationUrl: "https://goo.gl/maps/gyd"
    },
    {
        iata: "HAS",
        city: "Hail",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+966 16 532 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/has"
    },
    {
        iata: "HBE",
        city: "Alexandria",
        country: "Egypt",
        terminal: "Borg El Arab",
        timezone: "Africa/Cairo",
        distanceCenter: "40 km to City Center",
        nearbyAirports: "DBB: 100 km",
        phone: "+20 3 463 10 10",
        website: "http://eac-airports.com",
        locationUrl: "https://goo.gl/maps/hbe"
    },
    {
        iata: "HOF",
        city: "Hofuf",
        country: "Saudi Arabia",
        terminal: "Al-Ahsa Intl",
        timezone: "Asia/Riyadh",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "DMM: 150 km",
        phone: "+966 13 594 4000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/hof"
    },
    {
        iata: "HYD",
        city: "Hyderabad",
        country: "India",
        terminal: "International Terminal",
        timezone: "Asia/Kolkata",
        distanceCenter: "24 km to City Center",
        nearbyAirports: "None",
        phone: "+91 40 6654 6370",
        website: "https://www.hyderabad.aero",
        locationUrl: "https://goo.gl/maps/hyd"
    },
    {
        iata: "IFN",
        city: "Isfahan",
        country: "Iran",
        terminal: "International Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "25 km to City Center",
        nearbyAirports: "None",
        phone: "+98 31 3527 5050",
        website: "https://isfahan.airport.ir",
        locationUrl: "https://goo.gl/maps/ifn"
    },
    {
        iata: "IKA",
        city: "Tehran",
        country: "Iran",
        terminal: "Imam Khomeini Intl",
        timezone: "Asia/Tehran",
        distanceCenter: "30 km to City Center",
        nearbyAirports: "THR (Domestic)",
        phone: "+98 21 5100 118",
        website: "https://www.ikac.ir",
        locationUrl: "https://goo.gl/maps/ika"
    },
    {
        iata: "ISB",
        city: "Islamabad",
        country: "Pakistan",
        terminal: "International Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "20 km to City Center",
        nearbyAirports: "PEW: 180 km",
        phone: "+92 51 111 222 114",
        website: "https://islamabadairport.com.pk",
        locationUrl: "https://goo.gl/maps/isb"
    },
    {
        iata: "IST",
        city: "Istanbul",
        country: "Turkey",
        terminal: "Main International",
        timezone: "Europe/Istanbul",
        distanceCenter: "40 km to Taksim",
        nearbyAirports: "SAW: 85 km",
        phone: "+90 444 1 442",
        website: "https://www.istairport.com",
        locationUrl: "https://goo.gl/maps/ist"
    },
    {
        iata: "ISU",
        city: "Sulaymaniyah",
        country: "Iraq",
        terminal: "Main Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "EBL: 170 km",
        phone: "+964 53 312 0000",
        website: "http://www.sulairport.krd",
        locationUrl: "https://goo.gl/maps/isu"
    },
    {
        iata: "JED",
        city: "Jeddah",
        country: "Saudi Arabia",
        terminal: "Terminal 1",
        timezone: "Asia/Riyadh",
        distanceCenter: "19 km to Corniche",
        nearbyAirports: "None",
        phone: "+966 9200 11233",
        website: "https://jeddahairports.com",
        locationUrl: "https://goo.gl/maps/jed"
    },
    {
        iata: "JIB",
        city: "Djibouti",
        country: "Djibouti",
        terminal: "Ambouli Intl",
        timezone: "Africa/Nairobi",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+253 21 34 06 05",
        website: "https://aeroport-djibouti.com",
        locationUrl: "https://goo.gl/maps/jib"
    },
    {
        iata: "JMK",
        city: "Mykonos",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "4 km to Chora",
        nearbyAirports: "JTR: Ferry/Flight",
        phone: "+30 2289 079000",
        website: "https://www.jmk-airport.gr",
        locationUrl: "https://goo.gl/maps/jmk"
    },
    {
        iata: "JTR",
        city: "Santorini",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "5 km to Fira",
        nearbyAirports: "JMK: Ferry/Flight",
        phone: "+30 2286 028400",
        website: "https://www.jtr-airport.gr",
        locationUrl: "https://goo.gl/maps/jtr"
    },
    {
        iata: "KBV",
        city: "Krabi",
        country: "Thailand",
        terminal: "Terminal 1",
        timezone: "Asia/Bangkok",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "HKT: 140 km",
        phone: "+66 75 701 470",
        website: "https://minisite.airports.go.th/krabi",
        locationUrl: "https://goo.gl/maps/kbv"
    },
    {
        iata: "KER",
        city: "Kerman",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+98 34 3211 0031",
        website: "https://kerman.airport.ir",
        locationUrl: "https://goo.gl/maps/ker"
    },
    {
        iata: "KHI",
        city: "Karachi",
        country: "Pakistan",
        terminal: "Jinnah Intl",
        timezone: "Asia/Karachi",
        distanceCenter: "18 km to City Center",
        nearbyAirports: "None",
        phone: "+92 21 9907 1111",
        website: "https://karachiairport.com.pk",
        locationUrl: "https://goo.gl/maps/khi"
    },
    {
        iata: "KRK",
        city: "Krakow",
        country: "Poland",
        terminal: "Main Terminal",
        timezone: "Europe/Warsaw",
        distanceCenter: "11 km to Old Town",
        nearbyAirports: "None",
        phone: "+48 12 295 58 00",
        website: "https://www.krakowairport.pl",
        locationUrl: "https://goo.gl/maps/krk"
    },
    {
        iata: "KTM",
        city: "Kathmandu",
        country: "Nepal",
        terminal: "Tribhuvan Intl",
        timezone: "Asia/Kathmandu",
        distanceCenter: "6 km to Thamel",
        nearbyAirports: "None",
        phone: "+977 1 411 3033",
        website: "https://www.tiairport.com.np",
        locationUrl: "https://goo.gl/maps/ktm"
    },
    {
        iata: "KUF",
        city: "Samara",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Europe/Samara",
        distanceCenter: "35 km to City Center",
        nearbyAirports: "None",
        phone: "+7 846 966 50 55",
        website: "https://uwww.aero",
        locationUrl: "https://goo.gl/maps/kuf"
    },
    {
        iata: "KWI",
        city: "Kuwait City",
        country: "Kuwait",
        terminal: "Terminal 1 or Sheikh Saad",
        timezone: "Asia/Kuwait",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+965 2433 6699",
        website: "https://www.kuwaitairport.gov.kw",
        locationUrl: "https://goo.gl/maps/kwi"
    },
    {
        iata: "KZN",
        city: "Kazan",
        country: "Russia",
        terminal: "Terminal 1A",
        timezone: "Europe/Moscow",
        distanceCenter: "25 km to Kremlin",
        nearbyAirports: "None",
        phone: "+7 843 267 88 07",
        website: "https://kazan.aero",
        locationUrl: "https://goo.gl/maps/kzn"
    },
    {
        iata: "LED",
        city: "St. Petersburg",
        country: "Russia",
        terminal: "Pulkovo Terminal 1",
        timezone: "Europe/Moscow",
        distanceCenter: "23 km to City Center",
        nearbyAirports: "None",
        phone: "+7 812 337 38 22",
        website: "https://pulkovoairport.ru",
        locationUrl: "https://goo.gl/maps/led"
    },
    {
        iata: "LHE",
        city: "Lahore",
        country: "Pakistan",
        terminal: "Allama Iqbal Intl",
        timezone: "Asia/Karachi",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "ATD: 100 km",
        phone: "+92 42 9903 1000",
        website: "https://lahoreairport.com.pk",
        locationUrl: "https://goo.gl/maps/lhe"
    },
    {
        iata: "LJU",
        city: "Ljubljana",
        country: "Slovenia",
        terminal: "Main Terminal",
        timezone: "Europe/Ljubljana",
        distanceCenter: "24 km to City Center",
        nearbyAirports: "ZAG: 140 km",
        phone: "+386 4 20 61 000",
        website: "https://www.lju-airport.si",
        locationUrl: "https://goo.gl/maps/lju"
    },
    {
        iata: "LKO",
        city: "Lucknow",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+91 522 243 5404",
        website: "https://www.aai.aero",
        locationUrl: "https://goo.gl/maps/lko"
    },
    {
        iata: "LRR",
        city: "Lar",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "None",
        phone: "+98 71 5233 8222",
        website: "https://lar.airport.ir",
        locationUrl: "https://goo.gl/maps/lrr"
    },
    {
        iata: "LYP",
        city: "Faisalabad",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "LHE: 120 km",
        phone: "+92 41 111 222 114",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://goo.gl/maps/lyp"
    },
    {
        iata: "MBA",
        city: "Mombasa",
        country: "Kenya",
        terminal: "Terminal 1",
        timezone: "Africa/Nairobi",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+254 41 343 3211",
        website: "https://kaa.go.ke",
        locationUrl: "https://goo.gl/maps/mba"
    },
    {
        iata: "MCX",
        city: "Makhachkala",
        country: "Russia",
        terminal: "Main Terminal",
        timezone: "Europe/Moscow",
        distanceCenter: "20 km to City Center",
        nearbyAirports: "None",
        phone: "+7 8722 55 55 00",
        website: "https://mcx.aero",
        locationUrl: "https://goo.gl/maps/mcx"
    },
    {
        iata: "MCT",
        city: "Muscat",
        country: "Oman",
        terminal: "New Terminal",
        timezone: "Asia/Muscat",
        distanceCenter: "30 km to Muttrah",
        nearbyAirports: "None",
        phone: "+968 24 351234",
        website: "https://www.muscatairport.co.om",
        locationUrl: "https://goo.gl/maps/mct"
    },
    {
        iata: "MED",
        city: "Medina",
        country: "Saudi Arabia",
        terminal: "International Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "20 km to Haram",
        nearbyAirports: "None",
        phone: "+966 4 842 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/med"
    },
    {
        iata: "MHD",
        city: "Mashhad",
        country: "Iran",
        terminal: "International Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "10 km to Shrine",
        nearbyAirports: "None",
        phone: "+98 51 3340 0001",
        website: "https://mashhad.airport.ir",
        locationUrl: "https://goo.gl/maps/mhd"
    },
    {
        iata: "MLE",
        city: "Male",
        country: "Maldives",
        terminal: "Velana Intl",
        timezone: "Indian/Maldives",
        distanceCenter: "Island Airport",
        nearbyAirports: "None",
        phone: "+960 332 3211",
        website: "https://macl.aero",
        locationUrl: "https://goo.gl/maps/mle"
    },
    {
        iata: "MRV",
        city: "Mineralnye Vody",
        country: "Russia",
        terminal: "Main Terminal",
        timezone: "Europe/Moscow",
        distanceCenter: "4 km to City Center",
        nearbyAirports: "None",
        phone: "+7 879 222 07 77",
        website: "https://mvairport.ru",
        locationUrl: "https://goo.gl/maps/mrv"
    },
    {
        iata: "MUX",
        city: "Multan",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+92 61 9200 301",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://goo.gl/maps/mux"
    },
    {
        iata: "NAP",
        city: "Naples",
        country: "Italy",
        terminal: "Terminal 1",
        timezone: "Europe/Rome",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+39 081 789 6111",
        website: "https://www.aeroportodinapoli.it",
        locationUrl: "https://goo.gl/maps/nap"
    },
    {
        iata: "NBO",
        city: "Nairobi",
        country: "Kenya",
        terminal: "Terminal 1",
        timezone: "Africa/Nairobi",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "MBA: 400 km",
        phone: "+254 20 661 1000",
        website: "https://kaa.go.ke",
        locationUrl: "https://goo.gl/maps/nbo"
    },
    {
        iata: "NJF",
        city: "Najaf",
        country: "Iraq",
        terminal: "Main Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "BGW: 160 km",
        phone: "+964 33 360 000",
        website: "http://www.njf.iq",
        locationUrl: "https://goo.gl/maps/njf"
    },
    {
        iata: "NQZ",
        city: "Astana",
        country: "Kazakhstan",
        terminal: "Terminal 1",
        timezone: "Asia/Almaty",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "None",
        phone: "+7 7172 702 999",
        website: "https://nn-airport.kz",
        locationUrl: "https://goo.gl/maps/nqz"
    },
    {
        iata: "NUM",
        city: "Neom",
        country: "Saudi Arabia",
        terminal: "Neom Bay",
        timezone: "Asia/Riyadh",
        distanceCenter: "New Development",
        nearbyAirports: "TUU: 150 km",
        phone: "+966 14 420 0000",
        website: "https://neom.com",
        locationUrl: "https://goo.gl/maps/num"
    },
    {
        iata: "OLB",
        city: "Olbia",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "4 km to City Center",
        nearbyAirports: "None",
        phone: "+39 0789 563 444",
        website: "https://www.geasar.it",
        locationUrl: "https://goo.gl/maps/olb"
    },
    {
        iata: "OTP",
        city: "Bucharest",
        country: "Romania",
        terminal: "Departures",
        timezone: "Europe/Bucharest",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "BBU: 8 km",
        phone: "+40 21 204 1000",
        website: "https://www.bucharestairports.ro",
        locationUrl: "https://goo.gl/maps/otp"
    },
    {
        iata: "OVB",
        city: "Novosibirsk",
        country: "Russia",
        terminal: "Terminal B",
        timezone: "Asia/Novosibirsk",
        distanceCenter: "16 km to City Center",
        nearbyAirports: "None",
        phone: "+7 383 216 99 99",
        website: "https://tolmachevo.ru",
        locationUrl: "https://goo.gl/maps/ovb"
    },
    {
        iata: "PEN",
        city: "Penang",
        country: "Malaysia",
        terminal: "Main Terminal",
        timezone: "Asia/Kuala_Lumpur",
        distanceCenter: "16 km to George Town",
        nearbyAirports: "LGK: 120 km",
        phone: "+60 4 643 4411",
        website: "https://penangairport.com",
        locationUrl: "https://goo.gl/maps/pen"
    },
    {
        iata: "PEW",
        city: "Peshawar",
        country: "Pakistan",
        terminal: "International Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "ISB: 180 km",
        phone: "+92 91 921 1525",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://goo.gl/maps/pew"
    },
    {
        iata: "POZ",
        city: "Poznan",
        country: "Poland",
        terminal: "Main Terminal",
        timezone: "Europe/Warsaw",
        distanceCenter: "7 km to City Center",
        nearbyAirports: "None",
        phone: "+48 61 849 23 43",
        website: "https://poznan-airport.com.pl",
        locationUrl: "https://goo.gl/maps/poz"
    },
    {
        iata: "PRG",
        city: "Prague",
        country: "Czech Republic",
        terminal: "Terminal 1",
        timezone: "Europe/Prague",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+420 220 111 888",
        website: "https://www.prg.aero",
        locationUrl: "https://goo.gl/maps/prg"
    },
    {
        iata: "PSA",
        city: "Pisa",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "2 km to City Center",
        nearbyAirports: "FLR: 80 km",
        phone: "+39 050 849 111",
        website: "https://www.pisa-airport.com",
        locationUrl: "https://goo.gl/maps/psa"
    },
    {
        iata: "RSI",
        city: "Red Sea",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "Resort Area",
        nearbyAirports: "YNB: 150 km",
        phone: "+966 14 420 1111",
        website: "https://redseaglobal.com",
        locationUrl: "https://goo.gl/maps/rsi"
    },
    {
        iata: "RUH",
        city: "Riyadh",
        country: "Saudi Arabia",
        terminal: "Terminal 2",
        timezone: "Asia/Riyadh",
        distanceCenter: "35 km to City Center",
        nearbyAirports: "None",
        phone: "+966 9200 20090",
        website: "https://kkia.sa",
        locationUrl: "https://goo.gl/maps/ruh"
    },
    {
        iata: "SAW",
        city: "Istanbul",
        country: "Turkey",
        terminal: "Sabiha Gokcen",
        timezone: "Europe/Istanbul",
        distanceCenter: "40 km to Kadikoy",
        nearbyAirports: "IST: 85 km",
        phone: "+90 216 588 88 88",
        website: "https://www.sabihagokcen.aero",
        locationUrl: "https://goo.gl/maps/saw"
    },
    {
        iata: "SJJ",
        city: "Sarajevo",
        country: "Bosnia & Herzegovina",
        terminal: "Main Terminal",
        timezone: "Europe/Sarajevo",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+387 33 289 100",
        website: "https://www.sarajevo-airport.ba",
        locationUrl: "https://goo.gl/maps/sjj"
    },
    {
        iata: "SKD",
        city: "Samarkand",
        country: "Uzbekistan",
        terminal: "New Terminal",
        timezone: "Asia/Samarkand",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+998 66 230 86 41",
        website: "https://ssl.uz",
        locationUrl: "https://goo.gl/maps/skd"
    },
    {
        iata: "SKT",
        city: "Sialkot",
        country: "Pakistan",
        terminal: "International Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "20 km to City Center",
        nearbyAirports: "LHE: 130 km",
        phone: "+92 52 111 742 575",
        website: "https://sialkotairport.com.pk",
        locationUrl: "https://goo.gl/maps/skt"
    },
    {
        iata: "SLL",
        city: "Salalah",
        country: "Oman",
        terminal: "New Terminal",
        timezone: "Asia/Muscat",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "None",
        phone: "+968 23 368 002",
        website: "https://salalahairport.co.om",
        locationUrl: "https://goo.gl/maps/sll"
    },
    {
        iata: "SOF",
        city: "Sofia",
        country: "Bulgaria",
        terminal: "Terminal 2",
        timezone: "Europe/Sofia",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "None",
        phone: "+359 2 937 2211",
        website: "https://sofia-airport.eu",
        locationUrl: "https://goo.gl/maps/sof"
    },
    {
        iata: "SPX",
        city: "Giza / Cairo",
        country: "Egypt",
        terminal: "Main Terminal",
        timezone: "Africa/Cairo",
        distanceCenter: "45 km to Downtown",
        nearbyAirports: "CAI: 65 km",
        phone: "+20 2 3344 5555",
        website: "http://www.civilaviation.gov.eg",
        locationUrl: "https://goo.gl/maps/spx"
    },
    {
        iata: "SVX",
        city: "Yekaterinburg",
        country: "Russia",
        terminal: "Terminal B",
        timezone: "Asia/Yekaterinburg",
        distanceCenter: "16 km to City Center",
        nearbyAirports: "None",
        phone: "+7 343 226 85 82",
        website: "https://svx.aero",
        locationUrl: "https://goo.gl/maps/svx"
    },
    {
        iata: "SYZ",
        city: "Shiraz",
        country: "Iran",
        terminal: "International Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "None",
        phone: "+98 71 3323 1800",
        website: "https://shiraz.airport.ir",
        locationUrl: "https://goo.gl/maps/syz"
    },
    {
        iata: "SZG",
        city: "Salzburg",
        country: "Austria",
        terminal: "Terminal 1",
        timezone: "Europe/Vienna",
        distanceCenter: "4 km to City Center",
        nearbyAirports: "MUC: 180 km",
        phone: "+43 662 8580 0",
        website: "https://www.salzburg-airport.com",
        locationUrl: "https://goo.gl/maps/szg"
    },
    {
        iata: "TAS",
        city: "Tashkent",
        country: "Uzbekistan",
        terminal: "Terminal 2",
        timezone: "Asia/Tashkent",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+998 78 140 28 01",
        website: "https://tashkent-airport.uz",
        locationUrl: "https://goo.gl/maps/tas"
    },
    {
        iata: "TBS",
        city: "Tbilisi",
        country: "Georgia",
        terminal: "Main Terminal",
        timezone: "Asia/Tbilisi",
        distanceCenter: "17 km to City Center",
        nearbyAirports: "None",
        phone: "+995 32 231 04 21",
        website: "https://www.tbilisiairport.com",
        locationUrl: "https://goo.gl/maps/tbs"
    },
    {
        iata: "TIF",
        city: "Taif",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "30 km to City Center",
        nearbyAirports: "None",
        phone: "+966 2 736 7777",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/tif"
    },
    {
        iata: "TIV",
        city: "Tivat",
        country: "Montenegro",
        terminal: "Terminal 1",
        timezone: "Europe/Podgorica",
        distanceCenter: "4 km to City Center",
        nearbyAirports: "DBV: 50 km",
        phone: "+382 32 671 337",
        website: "https://montenegroairports.com",
        locationUrl: "https://goo.gl/maps/tiv"
    },
    {
        iata: "TLV",
        city: "Tel Aviv",
        country: "Israel",
        terminal: "Terminal 3",
        timezone: "Asia/Jerusalem",
        distanceCenter: "20 km to City Center",
        nearbyAirports: "None",
        phone: "+972 3 978 3333",
        website: "https://www.iaa.gov.il",
        locationUrl: "https://goo.gl/maps/tlv"
    },
    {
        iata: "TUU",
        city: "Tabuk",
        country: "Saudi Arabia",
        terminal: "International Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "5 km to City Center",
        nearbyAirports: "None",
        phone: "+966 4 422 2300",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/tuu"
    },
    {
        iata: "TZX",
        city: "Trabzon",
        country: "Turkey",
        terminal: "Main Terminal",
        timezone: "Europe/Istanbul",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+90 462 328 09 40",
        website: "https://trabzon.dhmi.gov.tr",
        locationUrl: "https://goo.gl/maps/tzx"
    },
    {
        iata: "UET",
        city: "Quetta",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "12 km to City Center",
        nearbyAirports: "None",
        phone: "+92 81 924 1002",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://goo.gl/maps/uet"
    },
    {
        iata: "UFA",
        city: "Ufa",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Asia/Yekaterinburg",
        distanceCenter: "25 km to City Center",
        nearbyAirports: "None",
        phone: "+7 347 229 52 95",
        website: "https://airportufa.ru",
        locationUrl: "https://goo.gl/maps/ufa"
    },
    {
        iata: "UTP",
        city: "Pattaya",
        country: "Thailand",
        terminal: "U-Tapao Intl",
        timezone: "Asia/Bangkok",
        distanceCenter: "40 km to Pattaya Beach",
        nearbyAirports: "BKK: 140 km",
        phone: "+66 38 245 595",
        website: "http://www.utapao.com",
        locationUrl: "https://goo.gl/maps/utp"
    },
    {
        iata: "VKO",
        city: "Moscow",
        country: "Russia",
        terminal: "Terminal A",
        timezone: "Europe/Moscow",
        distanceCenter: "28 km to Red Square",
        nearbyAirports: "SVO: 50km | DME: 60km",
        phone: "+7 495 937 55 55",
        website: "http://www.vnukovo.ru",
        locationUrl: "https://goo.gl/maps/vko"
    },
    {
        iata: "VNO",
        city: "Vilnius",
        country: "Lithuania",
        terminal: "Main Terminal",
        timezone: "Europe/Vilnius",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+370 612 44442",
        website: "https://www.vilnius-airport.lt",
        locationUrl: "https://goo.gl/maps/vno"
    },
    {
        iata: "VOG",
        city: "Volgograd",
        country: "Russia",
        terminal: "Terminal C",
        timezone: "Europe/Volgograd",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+7 8442 26 10 87",
        website: "https://mav.ru",
        locationUrl: "https://goo.gl/maps/vog"
    },
    {
        iata: "WAW",
        city: "Warsaw",
        country: "Poland",
        terminal: "Chopin Terminal A",
        timezone: "Europe/Warsaw",
        distanceCenter: "10 km to City Center",
        nearbyAirports: "WMI: 40 km",
        phone: "+48 22 650 42 20",
        website: "https://www.lotnisko-chopina.pl",
        locationUrl: "https://goo.gl/maps/waw"
    },
    {
        iata: "YNB",
        city: "Yanbu",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "6 km to City Center",
        nearbyAirports: "None",
        phone: "+966 4 390 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://goo.gl/maps/ynb"
    },
    {
        iata: "ZAG",
        city: "Zagreb",
        country: "Croatia",
        terminal: "Main Terminal",
        timezone: "Europe/Zagreb",
        distanceCenter: "15 km to City Center",
        nearbyAirports: "None",
        phone: "+385 1 4562 170",
        website: "https://www.zagreb-airport.hr",
        locationUrl: "https://goo.gl/maps/zag"
    },
    {
        iata: "ZNZ",
        city: "Zanzibar",
        country: "Tanzania",
        terminal: "Terminal 3",
        timezone: "Africa/Dar_es_Salaam",
        distanceCenter: "7 km to Stone Town",
        nearbyAirports: "DAR: Ferry or Flight",
        phone: "+255 24 223 3979",
        website: "https://www.zaa.go.tz",
        locationUrl: "https://goo.gl/maps/znz"
    }
];
