const airportsData = [
    {
        iata: "ABH",
        city: "Abha",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "18 km to Center",
        nearbyAirports: "None",
        phone: "+966 17 224 6011",
        website: "https://gaca.gov.sa/web/en-gb/airport/abha-international-airport",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=ABH+Airport"
    },
    {
        iata: "ABJ",
        city: "Abidjan",
        country: "Ivory Coast",
        terminal: "Main Terminal",
        timezone: "Africa/Abidjan",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+225 21 75 79 01",
        website: "https://www.aeroport-abidjan.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Abidjan+Airport"
    },
    {
        iata: "ACC",
        city: "Accra",
        country: "Ghana",
        terminal: "Terminal 3",
        timezone: "Africa/Accra",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+233 30 277 6171",
        website: "https://www.gacl.com.gh",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kotoka+International+Airport"
    },
    {
        iata: "ADD",
        city: "Addis Ababa",
        country: "Ethiopia",
        terminal: "Terminal 2",
        timezone: "Africa/Addis_Ababa",
        distanceCenter: "6 km to Bole",
        nearbyAirports: "None",
        phone: "+251 11 665 0400",
        website: "https://addisairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Addis+Ababa+Bole+Airport"
    },
    {
        iata: "ADL",
        city: "Adelaide",
        country: "Australia",
        terminal: "Main Terminal",
        timezone: "Australia/Adelaide",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+61 8 8308 9211",
        website: "https://www.adelaideairport.com.au",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Adelaide+Airport"
    },
    {
        iata: "AER",
        city: "Sochi",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Europe/Moscow",
        distanceCenter: "28 km to Center",
        nearbyAirports: "None",
        phone: "+7 800 301 19 91",
        website: "https://aer.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sochi+Airport"
    },
    {
        iata: "AKL",
        city: "Auckland",
        country: "New Zealand",
        terminal: "International",
        timezone: "Pacific/Auckland",
        distanceCenter: "21 km to Center",
        nearbyAirports: "None",
        phone: "+64 9 275 0789",
        website: "https://www.aucklandairport.co.nz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Auckland+Airport"
    },
    {
        iata: "ALA",
        city: "Almaty",
        country: "Kazakhstan",
        terminal: "International",
        timezone: "Asia/Almaty",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+7 727 270 3333",
        website: "https://alaport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Almaty+Airport"
    },
    {
        iata: "ALG",
        city: "Algiers",
        country: "Algeria",
        terminal: "Terminal I",
        timezone: "Africa/Algiers",
        distanceCenter: "17 km to Center",
        nearbyAirports: "None",
        phone: "+213 21 50 91 91",
        website: "https://www.aeroportalger.dz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Algiers+Airport"
    },
    {
        iata: "AMD",
        city: "Ahmedabad",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "9 km to Center",
        nearbyAirports: "None",
        phone: "+91 79 2286 9211",
        website: "https://www.svpia.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ahmedabad+Airport"
    },
    {
        iata: "AMM",
        city: "Amman",
        country: "Jordan",
        terminal: "Terminal 1",
        timezone: "Asia/Amman",
        distanceCenter: "30 km to Center",
        nearbyAirports: "ADJ (Civil Only)",
        phone: "+962 6 401 0250",
        website: "https://www.qaiairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Queen+Alia+Airport"
    },
    {
        iata: "AMS",
        city: "Amsterdam",
        country: "Netherlands",
        terminal: "Main Terminal",
        timezone: "Europe/Amsterdam",
        distanceCenter: "9 km to Center",
        nearbyAirports: "RTM: 60km",
        phone: "+31 20 794 0800",
        website: "https://www.schiphol.nl",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Schiphol+Airport"
    },
    {
        iata: "ARN",
        city: "Stockholm",
        country: "Sweden",
        terminal: "Terminal 5",
        timezone: "Europe/Stockholm",
        distanceCenter: "40 km to Center",
        nearbyAirports: "BMA: 40km",
        phone: "+46 10 109 10 00",
        website: "https://www.swedavia.com/arlanda",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Arlanda+Airport"
    },
    {
        iata: "ASB",
        city: "Ashgabat",
        country: "Turkmenistan",
        terminal: "Main Terminal",
        timezone: "Asia/Ashgabat",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+993 12 23 20 34",
        website: "https://ashgabatairport.gov.tm",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ashgabat+Airport"
    },
    {
        iata: "ATH",
        city: "Athens",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+30 21 0353 0000",
        website: "https://www.aja.gr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Athens+Airport"
    },
    {
        iata: "AUH",
        city: "Abu Dhabi",
        country: "UAE",
        terminal: "Terminal A",
        timezone: "Asia/Dubai",
        distanceCenter: "30 km to Center",
        nearbyAirports: "DXB: 115km",
        phone: "+971 2 505 5555",
        website: "https://www.abudhabiairport.ae",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Abu+Dhabi+Airport"
    },
    {
        iata: "AYT",
        city: "Antalya",
        country: "Turkey",
        terminal: "Terminal 1",
        timezone: "Europe/Istanbul",
        distanceCenter: "13 km to Center",
        nearbyAirports: "None",
        phone: "+90 242 330 30 30",
        website: "https://www.antalya-airport.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Antalya+Airport"
    },
    {
        iata: "BAH",
        city: "Manama",
        country: "Bahrain",
        terminal: "Main Terminal",
        timezone: "Asia/Bahrain",
        distanceCenter: "7 km to Center",
        nearbyAirports: "DMM: 85km",
        phone: "+973 1733 9339",
        website: "https://www.bahrainairport.bh",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Bahrain+Airport"
    },
    {
        iata: "BCN",
        city: "Barcelona",
        country: "Spain",
        terminal: "Terminal 1",
        timezone: "Europe/Madrid",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+34 913 21 10 00",
        website: "https://www.aena.es/en/josep-tarradellas-barcelona-el-prat.html",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Barcelona+Airport"
    },
    {
        iata: "BEG",
        city: "Belgrade",
        country: "Serbia",
        terminal: "Terminal 2",
        timezone: "Europe/Belgrade",
        distanceCenter: "18 km to Center",
        nearbyAirports: "None",
        phone: "+381 11 209 4000",
        website: "https://beg.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Belgrade+Airport"
    },
    {
        iata: "BEY",
        city: "Beirut",
        country: "Lebanon",
        terminal: "Main Terminal",
        timezone: "Asia/Beirut",
        distanceCenter: "9 km to Center",
        nearbyAirports: "None",
        phone: "+961 1 628 000",
        website: "http://www.beirutairport.gov.lb",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Beirut+Rafic+Hariri+Airport"
    },
    {
        iata: "BGW",
        city: "Baghdad",
        country: "Iraq",
        terminal: "Babylon Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+964 0790 140 3537",
        website: "http://www.baghdadairport.info",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Baghdad+International+Airport"
    },
    {
        iata: "BGY",
        city: "Milan / Bergamo",
        country: "Italy",
        terminal: "Bergamo Orio",
        timezone: "Europe/Rome",
        distanceCenter: "45 km to Milan",
        nearbyAirports: "MXP: 90km",
        phone: "+39 035 326323",
        website: "https://www.milanbergamoairport.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Orio+al+Serio+Airport"
    },
    {
        iata: "BHX",
        city: "Birmingham",
        country: "UK",
        terminal: "Main Terminal",
        timezone: "Europe/London",
        distanceCenter: "13 km to Center",
        nearbyAirports: "EMA: 60km",
        phone: "+44 871 222 0072",
        website: "https://www.birminghamairport.co.uk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Birmingham+Airport"
    },
    {
        iata: "BJV",
        city: "Bodrum",
        country: "Turkey",
        terminal: "International",
        timezone: "Europe/Istanbul",
        distanceCenter: "36 km to Center",
        nearbyAirports: "DLM: 200km",
        phone: "+90 252 523 01 01",
        website: "http://www.milas-bodrumairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Milas+Bodrum+Airport"
    },
    {
        iata: "BKK",
        city: "Bangkok",
        country: "Thailand",
        terminal: "Main Terminal",
        timezone: "Asia/Bangkok",
        distanceCenter: "30 km to Center",
        nearbyAirports: "DMK: 45km",
        phone: "+66 2 132 1888",
        website: "https://suvarnabhumi.airportthai.co.th",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Suvarnabhumi+Airport"
    },
    {
        iata: "BLR",
        city: "Bengaluru",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "40 km to Center",
        nearbyAirports: "None",
        phone: "+91 80 2201 2001",
        website: "https://www.bengaluruairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kempegowda+International+Airport"
    },
    {
        iata: "BNE",
        city: "Brisbane",
        country: "Australia",
        terminal: "International",
        timezone: "Australia/Brisbane",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+61 7 3406 3000",
        website: "https://www.bne.com.au",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Brisbane+Airport"
    },
    {
        iata: "BOM",
        city: "Mumbai",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+91 22 6685 1010",
        website: "https://csmia.adaniairports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mumbai+Airport"
    },
    {
        iata: "BOS",
        city: "Boston",
        country: "USA",
        terminal: "Terminal E",
        timezone: "America/New_York",
        distanceCenter: "5 km to Center",
        nearbyAirports: "None",
        phone: "+1 800 235 6426",
        website: "https://www.massport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Logan+Airport"
    },
    {
        iata: "BRU",
        city: "Brussels",
        country: "Belgium",
        terminal: "Main Terminal",
        timezone: "Europe/Brussels",
        distanceCenter: "12 km to Center",
        nearbyAirports: "CRL: 45km",
        phone: "+32 2 753 77 53",
        website: "https://www.brusselsairport.be",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Brussels+Airport"
    },
    {
        iata: "BSL",
        city: "Basel / Mulhouse",
        country: "Switzerland / France",
        terminal: "Bi-National",
        timezone: "Europe/Zurich",
        distanceCenter: "6 km to Basel | 20 km to Mulhouse",
        nearbyAirports: "ZRH: 85km",
        phone: "+33 3 89 90 31 11",
        website: "https://www.euroairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Basel+Mulhouse+Airport"
    },
    {
        iata: "BSR",
        city: "Basra",
        country: "Iraq",
        terminal: "Main Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+964 40 888 123",
        website: "https://www.basraairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Basra+Airport"
    },
    {
        iata: "BSZ",
        city: "Bishkek",
        country: "Kyrgyzstan",
        terminal: "Manas Intl",
        timezone: "Asia/Bishkek",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+996 312 693 109",
        website: "http://www.airport.kg",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Manas+Airport"
    },
    {
        iata: "BUD",
        city: "Budapest",
        country: "Hungary",
        terminal: "Terminal 2B",
        timezone: "Europe/Budapest",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+36 1 296 7000",
        website: "https://www.bud.hu",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Budapest+Airport"
    },
    {
        iata: "CAI",
        city: "Cairo",
        country: "Egypt",
        terminal: "Terminal 2/3",
        timezone: "Africa/Cairo",
        distanceCenter: "20 km to Center",
        nearbyAirports: "SPX: 65km",
        phone: "+20 2 2265 5000",
        website: "https://www.cairo-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Cairo+International+Airport"
    },
    {
        iata: "CAN",
        city: "Guangzhou",
        country: "China",
        terminal: "Terminal 2",
        timezone: "Asia/Shanghai",
        distanceCenter: "28 km to Center",
        nearbyAirports: "None",
        phone: "+86 20 96158",
        website: "https://www.gbiac.net",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Guangzhou+Baiyun+Airport"
    },
    {
        iata: "CCJ",
        city: "Kozhikode",
        country: "India",
        terminal: "International",
        timezone: "Asia/Kolkata",
        distanceCenter: "28 km to Center",
        nearbyAirports: "COK: 160km",
        phone: "+91 483 271 2630",
        website: "https://www.aai.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Calicut+International+Airport"
    },
    {
        iata: "CCU",
        city: "Kolkata",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "17 km to Center",
        nearbyAirports: "None",
        phone: "+91 33 2511 8036",
        website: "https://www.aai.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kolkata+Airport"
    },
    {
        iata: "CDG",
        city: "Paris",
        country: "France",
        terminal: "Terminal 2C",
        timezone: "Europe/Paris",
        distanceCenter: "25 km to Center",
        nearbyAirports: "ORY: 40km",
        phone: "+33 1 70 36 39 50",
        website: "https://www.parisaeroport.fr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Charles+de+Gaulle+Airport"
    },
    {
        iata: "CEB",
        city: "Cebu",
        country: "Philippines",
        terminal: "Terminal 2",
        timezone: "Asia/Manila",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+63 32 340 2486",
        website: "https://www.mactancebuairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mactan-Cebu+Airport"
    },
    {
        iata: "CFU",
        city: "Corfu",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "2 km to Center",
        nearbyAirports: "None",
        phone: "+30 2661 089600",
        website: "https://www.cfu-airport.gr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Corfu+Airport"
    },
    {
        iata: "CHC",
        city: "Christchurch",
        country: "New Zealand",
        terminal: "International",
        timezone: "Pacific/Auckland",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+64 3 353 7777",
        website: "https://www.christchurchairport.co.nz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Christchurch+Airport"
    },
    {
        iata: "CIT",
        city: "Shymkent",
        country: "Kazakhstan",
        terminal: "Main Terminal",
        timezone: "Asia/Almaty",
        distanceCenter: "12 km to Center",
        nearbyAirports: "TAS: 120km",
        phone: "+7 7252 45 50 30",
        website: "http://airserver.kz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Shymkent+Airport"
    },
    {
        iata: "CMB",
        city: "Colombo",
        country: "Sri Lanka",
        terminal: "Main Terminal",
        timezone: "Asia/Colombo",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+94 11 225 2861",
        website: "https://www.airport.lk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Bandaranaike+Airport"
    },
    {
        iata: "CMN",
        city: "Casablanca",
        country: "Morocco",
        terminal: "Terminal 2",
        timezone: "Africa/Casablanca",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+212 5225-39040",
        website: "http://www.onda.ma",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Casablanca+Mohammed+V+Airport"
    },
    {
        iata: "COK",
        city: "Kochi",
        country: "India",
        terminal: "Terminal 3",
        timezone: "Asia/Kolkata",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+91 484 261 0115",
        website: "https://www.cial.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Cochin+Airport"
    },
    {
        iata: "CPT",
        city: "Cape Town",
        country: "South Africa",
        terminal: "International",
        timezone: "Africa/Johannesburg",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+27 21 937 1200",
        website: "https://www.airports.co.za",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Cape+Town+Airport"
    },
    {
        iata: "CRK",
        city: "Clark",
        country: "Philippines",
        terminal: "Terminal 2",
        timezone: "Asia/Manila",
        distanceCenter: "5 km to Center",
        nearbyAirports: "MNL: 100km",
        phone: "+63 45 599 2888",
        website: "https://clarkinternationalairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Clark+International+Airport"
    },
    {
        iata: "CTA",
        city: "Catania",
        country: "Italy",
        terminal: "Terminal A",
        timezone: "Europe/Rome",
        distanceCenter: "4 km to Center",
        nearbyAirports: "PMO: 240km",
        phone: "+39 095 723 9111",
        website: "https://www.aeroporto.catania.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Catania+Airport"
    },
    {
        iata: "DAC",
        city: "Dhaka",
        country: "Bangladesh",
        terminal: "Terminal 2",
        timezone: "Asia/Dhaka",
        distanceCenter: "17 km to Center",
        nearbyAirports: "None",
        phone: "+880 2 7911042",
        website: "http://caab.gov.bd",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dhaka+Airport"
    },
    {
        iata: "DAM",
        city: "Damascus",
        country: "Syria",
        terminal: "Main Terminal",
        timezone: "Asia/Damascus",
        distanceCenter: "30 km to Center",
        nearbyAirports: "BEY: 110km",
        phone: "+963 11 540 0000",
        website: "http://www.damascus-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Damascus+International+Airport"
    },
    {
        iata: "DAR",
        city: "Dar es Salaam",
        country: "Tanzania",
        terminal: "Terminal 3",
        timezone: "Africa/Dar_es_Salaam",
        distanceCenter: "12 km to Center",
        nearbyAirports: "ZNZ: 70km (Ferry)",
        phone: "+255 22 284 4371",
        website: "https://www.taa.go.tz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Julius+Nyerere+International+Airport"
    },
    {
        iata: "DBB",
        city: "Al Alamein",
        country: "Egypt",
        terminal: "Main Terminal",
        timezone: "Africa/Cairo",
        distanceCenter: "30 km to Marina",
        nearbyAirports: "HBE: 100km",
        phone: "+20 46 410 0000",
        website: "http://eac-airports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Al+Alamein+International+Airport"
    },
    {
        iata: "DBV",
        city: "Dubrovnik",
        country: "Croatia",
        terminal: "Main Terminal",
        timezone: "Europe/Zagreb",
        distanceCenter: "15 km to Center",
        nearbyAirports: "TIV: 50km",
        phone: "+385 20 773 100",
        website: "https://www.airport-dubrovnik.hr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dubrovnik+Airport"
    },
    {
        iata: "DEL",
        city: "Delhi",
        country: "India",
        terminal: "Terminal 3",
        timezone: "Asia/Kolkata",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+91 124 3376000",
        website: "https://www.newdelhiairport.in",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Delhi+Airport"
    },
    {
        iata: "DFW",
        city: "Dallas",
        country: "USA",
        terminal: "Terminal D",
        timezone: "America/Chicago",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+1 972 973 3112",
        website: "https://www.dfwairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=DFW+Airport"
    },
    {
        iata: "DMM",
        city: "Dammam",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "30 km to Center",
        nearbyAirports: "BAH: 85km",
        phone: "+966 13 883 4444",
        website: "https://kfia.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dammam+Airport"
    },
    {
        iata: "DOH",
        city: "Doha",
        country: "Qatar",
        terminal: "Hamad Intl",
        timezone: "Asia/Qatar",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+974 4010 6666",
        website: "https://dohahamadairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Hamad+International+Airport"
    },
    {
        iata: "DPS",
        city: "Bali",
        country: "Indonesia",
        terminal: "International",
        timezone: "Asia/Makassar",
        distanceCenter: "13 km to Denpasar",
        nearbyAirports: "None",
        phone: "+62 361 935 1011",
        website: "https://www.bali-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Bali+Airport"
    },
    {
        iata: "DSS",
        city: "Dakar",
        country: "Senegal",
        terminal: "Main Terminal",
        timezone: "Africa/Dakar",
        distanceCenter: "45 km to Center",
        nearbyAirports: "None",
        phone: "+221 33 939 69 00",
        website: "https://www.dakaraeroport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Blaise+Diagne+Airport"
    },
    {
        iata: "DUB",
        city: "Dublin",
        country: "Ireland",
        terminal: "Terminal 2",
        timezone: "Europe/Dublin",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+353 1 814 1111",
        website: "https://www.dublinairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dublin+Airport"
    },
    {
        iata: "DUR",
        city: "Durban",
        country: "South Africa",
        terminal: "International",
        timezone: "Africa/Johannesburg",
        distanceCenter: "35 km to Center",
        nearbyAirports: "None",
        phone: "+27 32 436 6758",
        website: "https://www.airports.co.za",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=King+Shaka+Airport"
    },
    {
        iata: "DUS",
        city: "Dusseldorf",
        country: "Germany",
        terminal: "Terminal C",
        timezone: "Europe/Berlin",
        distanceCenter: "7 km to Center",
        nearbyAirports: "CGN: 50km",
        phone: "+49 211 4210",
        website: "https://www.dus.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dusseldorf+Airport"
    },
    {
        iata: "DWC",
        city: "Dubai World Central",
        country: "UAE",
        terminal: "Main Terminal",
        timezone: "Asia/Dubai",
        distanceCenter: "60 km to Center",
        nearbyAirports: "DXB: 60km",
        phone: "+971 4 224 5555",
        website: "https://www.dubaiairports.ae",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Al+Maktoum+Airport"
    },
    {
        iata: "DXB",
        city: "Dubai",
        country: "UAE",
        terminal: "T3 (EK) | T2 (FZ)",
        timezone: "Asia/Dubai",
        distanceCenter: "5 km to Center",
        nearbyAirports: "DWC: 60km",
        phone: "+971 4 224 5555",
        website: "https://www.dubaiairports.ae",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dubai+International+Airport"
    },
    {
        iata: "DYU",
        city: "Dushanbe",
        country: "Tajikistan",
        terminal: "Main Terminal",
        timezone: "Asia/Dushanbe",
        distanceCenter: "5 km to Center",
        nearbyAirports: "None",
        phone: "+992 47 449 4233",
        website: "http://airport.tj",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dushanbe+Airport"
    },
    {
        iata: "EAM",
        city: "Najran",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "26 km to Center",
        nearbyAirports: "None",
        phone: "+966 7 544 0444",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Najran+Airport"
    },
    {
        iata: "EBB",
        city: "Entebbe",
        country: "Uganda",
        terminal: "Main Terminal",
        timezone: "Africa/Kampala",
        distanceCenter: "40 km to Kampala",
        nearbyAirports: "None",
        phone: "+256 31 235 2000",
        website: "https://caa.go.ug",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Entebbe+Airport"
    },
    {
        iata: "EBL",
        city: "Erbil",
        country: "Iraq",
        terminal: "International",
        timezone: "Asia/Baghdad",
        distanceCenter: "7 km to Center",
        nearbyAirports: "ISU: 170km",
        phone: "+964 66 281 0000",
        website: "https://www.erbilairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Erbil+Airport"
    },
    {
        iata: "EDI",
        city: "Edinburgh",
        country: "UK",
        terminal: "Main Terminal",
        timezone: "Europe/London",
        distanceCenter: "13 km to Center",
        nearbyAirports: "GLA: 70km",
        phone: "+44 844 448 8833",
        website: "https://www.edinburghairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Edinburgh+Airport"
    },
    {
        iata: "ELQ",
        city: "Gassim",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "25 km to Buraydah",
        nearbyAirports: "None",
        phone: "+966 6 380 0055",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Prince+Nayef+Airport"
    },
    {
        iata: "ESB",
        city: "Ankara",
        country: "Turkey",
        terminal: "International",
        timezone: "Europe/Istanbul",
        distanceCenter: "28 km to Center",
        nearbyAirports: "None",
        phone: "+90 312 398 00 00",
        website: "https://www.esenbogaairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Esenboga+Airport"
    },
    {
        iata: "EVN",
        city: "Yerevan",
        country: "Armenia",
        terminal: "Zvartnots Intl",
        timezone: "Asia/Yerevan",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+374 10 493 000",
        website: "http://www.zvartnots.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Zvartnots+Airport"
    },
    {
        iata: "EWR",
        city: "Newark",
        country: "USA",
        terminal: "Terminal B",
        timezone: "America/New_York",
        distanceCenter: "20 km to NYC",
        nearbyAirports: "JFK: 35km",
        phone: "+1 973 961 6000",
        website: "https://www.newarkairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Newark+Airport"
    },
    {
        iata: "FCO",
        city: "Rome",
        country: "Italy",
        terminal: "Terminal 3",
        timezone: "Europe/Rome",
        distanceCenter: "30 km to Center",
        nearbyAirports: "CIA: 30km",
        phone: "+39 06 65951",
        website: "https://www.adr.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Fiumicino+Airport"
    },
    {
        iata: "FRA",
        city: "Frankfurt",
        country: "Germany",
        terminal: "Terminal 2",
        timezone: "Europe/Berlin",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+49 180 6 372 4636",
        website: "https://www.frankfurt-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Frankfurt+Airport"
    },
    {
        iata: "GIZ",
        city: "Jizan",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "3 km to Center",
        nearbyAirports: "ABH: 200km",
        phone: "+966 7 322 2222",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Jizan+Airport"
    },
    {
        iata: "GLA",
        city: "Glasgow",
        country: "UK",
        terminal: "Main Terminal",
        timezone: "Europe/London",
        distanceCenter: "15 km to Center",
        nearbyAirports: "EDI: 70km",
        phone: "+44 844 481 5555",
        website: "https://www.glasgowairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Glasgow+Airport"
    },
    {
        iata: "GSM",
        city: "Qeshm Island",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "50 km to City",
        nearbyAirports: "BND: Ferry",
        phone: "+98 76 3533 5040",
        website: "http://qeshmairport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Qeshm+Airport"
    },
    {
        iata: "GVA",
        city: "Geneva",
        country: "Switzerland",
        terminal: "Main Terminal",
        timezone: "Europe/Zurich",
        distanceCenter: "4 km to Center",
        nearbyAirports: "None",
        phone: "+41 22 717 71 11",
        website: "https://www.gva.ch",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Geneva+Airport"
    },
    {
        iata: "GYD",
        city: "Baku",
        country: "Azerbaijan",
        terminal: "Terminal 1",
        timezone: "Asia/Baku",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+994 12 497 27 27",
        website: "https://airport.az",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Heydar+Aliyev+Airport"
    },
    {
        iata: "HAM",
        city: "Hamburg",
        country: "Germany",
        terminal: "Terminal 1",
        timezone: "Europe/Berlin",
        distanceCenter: "8 km to Center",
        nearbyAirports: "None",
        phone: "+49 40 50750",
        website: "https://www.hamburg-airport.de",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Hamburg+Airport"
    },
    {
        iata: "HAN",
        city: "Hanoi",
        country: "Vietnam",
        terminal: "Terminal 2",
        timezone: "Asia/Bangkok",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+84 24 3886 5041",
        website: "http://noibaiairport.vn",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Noi+Bai+Airport"
    },
    {
        iata: "HAS",
        city: "Hail",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+966 16 532 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Hail+Airport"
    },
    {
        iata: "HBE",
        city: "Alexandria",
        country: "Egypt",
        terminal: "Borg El Arab",
        timezone: "Africa/Cairo",
        distanceCenter: "40 km to Center",
        nearbyAirports: "DBB: 100km",
        phone: "+20 3 463 10 10",
        website: "http://eac-airports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Borg+El+Arab+Airport"
    },
    {
        iata: "HKG",
        city: "Hong Kong",
        country: "China",
        terminal: "Terminal 1",
        timezone: "Asia/Hong_Kong",
        distanceCenter: "30 km to Center",
        nearbyAirports: "SZX: 40km (Ferry)",
        phone: "+852 2181 8888",
        website: "https://www.hongkongairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Hong+Kong+Airport"
    },
    {
        iata: "HKT",
        city: "Phuket",
        country: "Thailand",
        terminal: "International",
        timezone: "Asia/Bangkok",
        distanceCenter: "32 km to Center",
        nearbyAirports: "KBV: 140km",
        phone: "+66 76 351 166",
        website: "https://phuket.airportthai.co.th",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Phuket+Airport"
    },
    {
        iata: "HND",
        city: "Tokyo",
        country: "Japan",
        terminal: "Terminal 3",
        timezone: "Asia/Tokyo",
        distanceCenter: "15 km to Center",
        nearbyAirports: "NRT: 60km",
        phone: "+81 3 5757 8111",
        website: "https://tokyo-haneda.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Haneda+Airport"
    },
    {
        iata: "HOF",
        city: "Hofuf",
        country: "Saudi Arabia",
        terminal: "Al-Ahsa Intl",
        timezone: "Asia/Riyadh",
        distanceCenter: "17 km to Center",
        nearbyAirports: "DMM: 150km",
        phone: "+966 13 594 4000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Al-Ahsa+Airport"
    },
    {
        iata: "HRE",
        city: "Harare",
        country: "Zimbabwe",
        terminal: "International",
        timezone: "Africa/Harare",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+263 24 257 5111",
        website: "https://caaz.co.zw",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Robert+Gabriel+Mugabe+Airport"
    },
    {
        iata: "HYD",
        city: "Hyderabad",
        country: "India",
        terminal: "Main Terminal",
        timezone: "Asia/Kolkata",
        distanceCenter: "24 km to Center",
        nearbyAirports: "None",
        phone: "+91 40 6654 6370",
        website: "https://www.hyderabad.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Hyderabad+Airport"
    },
    {
        iata: "IAD",
        city: "Washington DC",
        country: "USA",
        terminal: "Main Terminal",
        timezone: "America/New_York",
        distanceCenter: "40 km to Center",
        nearbyAirports: "DCA: 45km",
        phone: "+1 703 572 2700",
        website: "https://www.flydulles.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Dulles+Airport"
    },
    {
        iata: "IAH",
        city: "Houston",
        country: "USA",
        terminal: "Terminal D",
        timezone: "America/Chicago",
        distanceCenter: "35 km to Center",
        nearbyAirports: "HOU: 40km",
        phone: "+1 281 230 3100",
        website: "https://www.fly2houston.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=George+Bush+Intercontinental+Airport"
    },
    {
        iata: "ICN",
        city: "Seoul",
        country: "South Korea",
        terminal: "Terminal 1",
        timezone: "Asia/Seoul",
        distanceCenter: "50 km to Center",
        nearbyAirports: "GMP: 35km",
        phone: "+82 1577 2600",
        website: "https://www.airport.kr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Incheon+Airport"
    },
    {
        iata: "IFN",
        city: "Isfahan",
        country: "Iran",
        terminal: "International",
        timezone: "Asia/Tehran",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+98 31 3527 5050",
        website: "https://isfahan.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Isfahan+Airport"
    },
    {
        iata: "IKA",
        city: "Tehran",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "30 km to Center",
        nearbyAirports: "THR (Domestic)",
        phone: "+98 21 5100 118",
        website: "https://www.ikac.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Imam+Khomeini+Airport"
    },
    {
        iata: "ISB",
        city: "Islamabad",
        country: "Pakistan",
        terminal: "International",
        timezone: "Asia/Karachi",
        distanceCenter: "20 km to Center",
        nearbyAirports: "PEW: 180km",
        phone: "+92 51 111 222 114",
        website: "https://islamabadairport.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Islamabad+Airport"
    },
    {
        iata: "IST",
        city: "Istanbul",
        country: "Turkey",
        terminal: "Main Terminal",
        timezone: "Europe/Istanbul",
        distanceCenter: "40 km to Center",
        nearbyAirports: "SAW: 85km",
        phone: "+90 444 1 442",
        website: "https://www.istairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Istanbul+Airport"
    },
    {
        iata: "ISU",
        city: "Sulaymaniyah",
        country: "Iraq",
        terminal: "Main Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "15 km to Center",
        nearbyAirports: "EBL: 170km",
        phone: "+964 53 312 0000",
        website: "http://sulairport.krd",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sulaymaniyah+Airport"
    },
    {
        iata: "JED",
        city: "Jeddah",
        country: "Saudi Arabia",
        terminal: "Terminal 1",
        timezone: "Asia/Riyadh",
        distanceCenter: "19 km to Center",
        nearbyAirports: "None",
        phone: "+966 9200 11233",
        website: "https://jeddahairports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=King+Abdulaziz+International+Airport"
    },
    {
        iata: "JFK",
        city: "New York",
        country: "USA",
        terminal: "Terminal 4",
        timezone: "America/New_York",
        distanceCenter: "25 km to Manhattan",
        nearbyAirports: "EWR: 35km",
        phone: "+1 718 244 4444",
        website: "https://www.jfkairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=JFK+Airport"
    },
    {
        iata: "JIB",
        city: "Djibouti",
        country: "Djibouti",
        terminal: "Ambouli Intl",
        timezone: "Africa/Nairobi",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+253 21 34 06 05",
        website: "https://www.aeroport-djibouti.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Djibouti+Airport"
    },
    {
        iata: "JMK",
        city: "Mykonos",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "4 km to Chora",
        nearbyAirports: "JTR: Ferry/Flight",
        phone: "+30 2289 079000",
        website: "https://www.jmk-airport.gr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mykonos+Airport"
    },
    {
        iata: "JNB",
        city: "Johannesburg",
        country: "South Africa",
        terminal: "Terminal A",
        timezone: "Africa/Johannesburg",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+27 11 921 6262",
        website: "https://www.airports.co.za",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=OR+Tambo+Airport"
    },
    {
        iata: "JTR",
        city: "Santorini",
        country: "Greece",
        terminal: "Main Terminal",
        timezone: "Europe/Athens",
        distanceCenter: "5 km to Fira",
        nearbyAirports: "JMK: Ferry/Flight",
        phone: "+30 2286 028400",
        website: "https://www.jtr-airport.gr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Santorini+Airport"
    },
    {
        iata: "KBP",
        city: "Kyiv",
        country: "Ukraine",
        terminal: "Terminal D",
        timezone: "Europe/Kyiv",
        distanceCenter: "30 km to Center",
        nearbyAirports: "IEV: 40km",
        phone: "+380 44 281 7122",
        website: "https://kbp.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Boryspil+Airport"
    },
    {
        iata: "KBV",
        city: "Krabi",
        country: "Thailand",
        terminal: "International",
        timezone: "Asia/Bangkok",
        distanceCenter: "15 km to Center",
        nearbyAirports: "HKT: 140km",
        phone: "+66 75 701 470",
        website: "https://minisite.airports.go.th/krabi",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Krabi+Airport"
    },
    {
        iata: "KER",
        city: "Kerman",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+98 34 3211 0031",
        website: "https://kerman.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kerman+Airport"
    },
    {
        iata: "KHI",
        city: "Karachi",
        country: "Pakistan",
        terminal: "Jinnah Intl",
        timezone: "Asia/Karachi",
        distanceCenter: "18 km to Center",
        nearbyAirports: "None",
        phone: "+92 21 9907 1111",
        website: "https://karachiairport.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Karachi+Airport"
    },
    {
        iata: "KIX",
        city: "Osaka",
        country: "Japan",
        terminal: "Terminal 1",
        timezone: "Asia/Tokyo",
        distanceCenter: "40 km to Center",
        nearbyAirports: "ITM: 70km",
        phone: "+81 72 455 2500",
        website: "https://www.kansai-airport.or.jp",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kansai+Airport"
    },
    {
        iata: "KRK",
        city: "Krakow",
        country: "Poland",
        terminal: "Main Terminal",
        timezone: "Europe/Warsaw",
        distanceCenter: "11 km to Center",
        nearbyAirports: "None",
        phone: "+48 12 295 58 00",
        website: "https://www.krakowairport.pl",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Krakow+Airport"
    },
    {
        iata: "KRT",
        city: "Khartoum",
        country: "Sudan",
        terminal: "Main Terminal",
        timezone: "Africa/Khartoum",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+249 18 377 7160",
        website: "http://khartoum-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Khartoum+Airport"
    },
    {
        iata: "KTM",
        city: "Kathmandu",
        country: "Nepal",
        terminal: "Tribhuvan Intl",
        timezone: "Asia/Kathmandu",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+977 1 411 3033",
        website: "https://www.tiairport.com.np",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kathmandu+Airport"
    },
    {
        iata: "KUF",
        city: "Samara",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Europe/Samara",
        distanceCenter: "35 km to Center",
        nearbyAirports: "None",
        phone: "+7 846 966 50 55",
        website: "https://uwww.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kurumoch+Airport"
    },
    {
        iata: "KUL",
        city: "Kuala Lumpur",
        country: "Malaysia",
        terminal: "KLIA 1",
        timezone: "Asia/Kuala_Lumpur",
        distanceCenter: "45 km to Center",
        nearbyAirports: "SZB: 50km",
        phone: "+60 3 8776 2000",
        website: "https://klia.com.my",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kuala+Lumpur+Airport"
    },
    {
        iata: "KWI",
        city: "Kuwait City",
        country: "Kuwait",
        terminal: "T1 (Common) | T4 (KU)",
        timezone: "Asia/Kuwait",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+965 2433 6699",
        website: "https://www.kuwaitairport.gov.kw",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kuwait+Airport"
    },
    {
        iata: "KZN",
        city: "Kazan",
        country: "Russia",
        terminal: "Terminal 1A",
        timezone: "Europe/Moscow",
        distanceCenter: "25 km to Kremlin",
        nearbyAirports: "None",
        phone: "+7 843 267 88 07",
        website: "https://kazan.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Kazan+Airport"
    },
    {
        iata: "LAX",
        city: "Los Angeles",
        country: "USA",
        terminal: "TBIT",
        timezone: "America/Los_Angeles",
        distanceCenter: "30 km to Downtown",
        nearbyAirports: "LGB: 35km",
        phone: "+1 855 463 5252",
        website: "https://www.flylax.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=LAX+Airport"
    },
    {
        iata: "LED",
        city: "St. Petersburg",
        country: "Russia",
        terminal: "Pulkovo T1",
        timezone: "Europe/Moscow",
        distanceCenter: "23 km to Center",
        nearbyAirports: "None",
        phone: "+7 812 337 38 22",
        website: "https://pulkovoairport.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Pulkovo+Airport"
    },
    {
        iata: "LGW",
        city: "London Gatwick",
        country: "UK",
        terminal: "North Terminal",
        timezone: "Europe/London",
        distanceCenter: "45 km to London",
        nearbyAirports: "LHR: 45km",
        phone: "+44 344 892 0322",
        website: "https://www.gatwickairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Gatwick+Airport"
    },
    {
        iata: "LHE",
        city: "Lahore",
        country: "Pakistan",
        terminal: "Allama Iqbal",
        timezone: "Asia/Karachi",
        distanceCenter: "15 km to Center",
        nearbyAirports: "ATD: 100km",
        phone: "+92 42 9903 1000",
        website: "https://lahoreairport.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lahore+Airport"
    },
    {
        iata: "LHR",
        city: "London Heathrow",
        country: "UK",
        terminal: "Terminal 3",
        timezone: "Europe/London",
        distanceCenter: "23 km to London",
        nearbyAirports: "LGW: 45km",
        phone: "+44 844 335 1801",
        website: "https://www.heathrow.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Heathrow+Airport"
    },
    {
        iata: "LIS",
        city: "Lisbon",
        country: "Portugal",
        terminal: "Terminal 1",
        timezone: "Europe/Lisbon",
        distanceCenter: "7 km to Center",
        nearbyAirports: "None",
        phone: "+351 21 841 3500",
        website: "https://www.aeroportolisboa.pt",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lisbon+Airport"
    },
    {
        iata: "LJU",
        city: "Ljubljana",
        country: "Slovenia",
        terminal: "Main Terminal",
        timezone: "Europe/Ljubljana",
        distanceCenter: "24 km to Center",
        nearbyAirports: "ZAG: 140km",
        phone: "+386 4 20 61 000",
        website: "https://www.lju-airport.si",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ljubljana+Airport"
    },
    {
        iata: "LKO",
        city: "Lucknow",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+91 522 243 5404",
        website: "https://aai.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lucknow+Airport"
    },
    {
        iata: "LOS",
        city: "Lagos",
        country: "Nigeria",
        terminal: "Murtala Muhammed",
        timezone: "Africa/Lagos",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+234 1 493 3385",
        website: "https://faan.gov.ng",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lagos+Airport"
    },
    {
        iata: "LRR",
        city: "Lar",
        country: "Iran",
        terminal: "Main Terminal",
        timezone: "Asia/Tehran",
        distanceCenter: "5 km to Center",
        nearbyAirports: "None",
        phone: "+98 71 5233 8222",
        website: "https://lar.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lar+International+Airport"
    },
    {
        iata: "LUN",
        city: "Lusaka",
        country: "Zambia",
        terminal: "Terminal 2",
        timezone: "Africa/Lusaka",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+260 211 271359",
        website: "https://www.zacl.co.zm",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lusaka+Airport"
    },
    {
        iata: "LYO",
        city: "Lyon",
        country: "France",
        terminal: "Terminal 1",
        timezone: "Europe/Paris",
        distanceCenter: "20 km to Center",
        nearbyAirports: "GVA: 110km",
        phone: "+33 4 26 00 70 07",
        website: "https://www.lyonaeroports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Lyon+Saint+Exupery+Airport"
    },
    {
        iata: "LYP",
        city: "Faisalabad",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "10 km to Center",
        nearbyAirports: "LHE: 120km",
        phone: "+92 41 111 222 114",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Faisalabad+Airport"
    },
    {
        iata: "MAA",
        city: "Chennai",
        country: "India",
        terminal: "International",
        timezone: "Asia/Kolkata",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+91 44 2256 0551",
        website: "https://aai.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Chennai+Airport"
    },
    {
        iata: "MAD",
        city: "Madrid",
        country: "Spain",
        terminal: "Terminal 4S",
        timezone: "Europe/Madrid",
        distanceCenter: "13 km to Center",
        nearbyAirports: "None",
        phone: "+34 913 21 10 00",
        website: "https://www.aena.es/en/adolfo-suarez-madrid-barajas.html",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Madrid+Barajas+Airport"
    },
    {
        iata: "MAN",
        city: "Manchester",
        country: "UK",
        terminal: "Terminal 1",
        timezone: "Europe/London",
        distanceCenter: "15 km to Center",
        nearbyAirports: "LPL: 50km",
        phone: "+44 871 271 0711",
        website: "https://www.manchesterairport.co.uk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Manchester+Airport"
    },
    {
        iata: "MBA",
        city: "Mombasa",
        country: "Kenya",
        terminal: "Terminal 1",
        timezone: "Africa/Nairobi",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+254 41 343 3211",
        website: "https://kaa.go.ke",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Moi+International+Airport"
    },
    {
        iata: "MCO",
        city: "Orlando",
        country: "USA",
        terminal: "Terminal C",
        timezone: "America/New_York",
        distanceCenter: "20 km to Center",
        nearbyAirports: "SFB: 50km",
        phone: "+1 407 825 2001",
        website: "https://orlandoairports.net",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Orlando+International+Airport"
    },
    {
        iata: "MCT",
        city: "Muscat",
        country: "Oman",
        terminal: "New Terminal",
        timezone: "Asia/Muscat",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+968 24 351234",
        website: "https://www.muscatairport.co.om",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Muscat+Airport"
    },
    {
        iata: "MCX",
        city: "Makhachkala",
        country: "Russia",
        terminal: "Main Terminal",
        timezone: "Europe/Moscow",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+7 8722 55 55 00",
        website: "https://mcx.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Makhachkala+Airport"
    },
    {
        iata: "MED",
        city: "Medina",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "20 km to Haram",
        nearbyAirports: "None",
        phone: "+966 4 842 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Medina+Airport"
    },
    {
        iata: "MEL",
        city: "Melbourne",
        country: "Australia",
        terminal: "Terminal 2",
        timezone: "Australia/Melbourne",
        distanceCenter: "23 km to Center",
        nearbyAirports: "AVV: 55km",
        phone: "+61 3 9297 1600",
        website: "https://www.melbourneairport.com.au",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Melbourne+Airport"
    },
    {
        iata: "MEX",
        city: "Mexico City",
        country: "Mexico",
        terminal: "Terminal 1",
        timezone: "America/Mexico_City",
        distanceCenter: "10 km to Center",
        nearbyAirports: "NLU: 40km",
        phone: "+52 55 2482 2400",
        website: "https://www.aicm.com.mx",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mexico+City+Airport"
    },
    {
        iata: "MHD",
        city: "Mashhad",
        country: "Iran",
        terminal: "International",
        timezone: "Asia/Tehran",
        distanceCenter: "10 km to Shrine",
        nearbyAirports: "None",
        phone: "+98 51 3340 0001",
        website: "https://mashhad.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mashhad+Airport"
    },
    {
        iata: "MIA",
        city: "Miami",
        country: "USA",
        terminal: "South Terminal",
        timezone: "America/New_York",
        distanceCenter: "13 km to Center",
        nearbyAirports: "FLL: 35km",
        phone: "+1 305 876 7000",
        website: "https://www.miami-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Miami+International+Airport"
    },
    {
        iata: "MLE",
        city: "Male",
        country: "Maldives",
        terminal: "Velana Intl",
        timezone: "Indian/Maldives",
        distanceCenter: "Island Airport",
        nearbyAirports: "None",
        phone: "+960 332 3211",
        website: "https://macl.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Velana+International+Airport"
    },
    {
        iata: "MNL",
        city: "Manila",
        country: "Philippines",
        terminal: "Terminal 3",
        timezone: "Asia/Manila",
        distanceCenter: "10 km to Center",
        nearbyAirports: "CRK: 90km",
        phone: "+63 2 877 1109",
        website: "https://www.miaa.gov.ph",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ninoy+Aquino+International+Airport"
    },
    {
        iata: "MRU",
        city: "Mauritius",
        country: "Mauritius",
        terminal: "Main Terminal",
        timezone: "Indian/Mauritius",
        distanceCenter: "40 km to Port Louis",
        nearbyAirports: "None",
        phone: "+230 603 6000",
        website: "https://mauritius-airport.atol.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mauritius+Airport"
    },
    {
        iata: "MRV",
        city: "Mineralnye Vody",
        country: "Russia",
        terminal: "Main Terminal",
        timezone: "Europe/Moscow",
        distanceCenter: "4 km to Center",
        nearbyAirports: "None",
        phone: "+7 879 222 07 77",
        website: "https://mvairport.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mineralnye+Vody+Airport"
    },
    {
        iata: "MUC",
        city: "Munich",
        country: "Germany",
        terminal: "Terminal 1",
        timezone: "Europe/Berlin",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+49 89 97500",
        website: "https://www.munich-airport.de",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Munich+Airport"
    },
    {
        iata: "MULT",
        city: "Multan",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+92 61 9200 301",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Multan+Airport"
    },
    {
        iata: "MUX",
        city: "Multan",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+92 61 9200 301",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Multan+Airport"
    },
    {
        iata: "MXP",
        city: "Milan",
        country: "Italy",
        terminal: "Terminal 1",
        timezone: "Europe/Rome",
        distanceCenter: "50 km to Center",
        nearbyAirports: "LIN: 50km",
        phone: "+39 02 232323",
        website: "https://www.milanomalpensa-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Malpensa+Airport"
    },
    {
        iata: "NAP",
        city: "Naples",
        country: "Italy",
        terminal: "Terminal 1",
        timezone: "Europe/Rome",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+39 081 789 6111",
        website: "https://www.aeroportodinapoli.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Naples+Airport"
    },
    {
        iata: "NBO",
        city: "Nairobi",
        country: "Kenya",
        terminal: "Terminal 1",
        timezone: "Africa/Nairobi",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+254 20 661 1000",
        website: "https://kaa.go.ke",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Nairobi+Airport"
    },
    {
        iata: "NCE",
        city: "Nice",
        country: "France",
        terminal: "Terminal 2",
        timezone: "Europe/Paris",
        distanceCenter: "7 km to Center",
        nearbyAirports: "None",
        phone: "+33 820 42 33 33",
        website: "https://www.nice.aeroport.fr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Nice+Airport"
    },
    {
        iata: "NJF",
        city: "Najaf",
        country: "Iraq",
        terminal: "Main Terminal",
        timezone: "Asia/Baghdad",
        distanceCenter: "10 km to Center",
        nearbyAirports: "BGW: 160km",
        phone: "+964 33 360 000",
        website: "http://njf.iq",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Najaf+Airport"
    },
    {
        iata: "NQZ",
        city: "Astana",
        country: "Kazakhstan",
        terminal: "Terminal 1",
        timezone: "Asia/Almaty",
        distanceCenter: "17 km to Center",
        nearbyAirports: "None",
        phone: "+7 7172 702 999",
        website: "https://nn-airport.kz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Nursultan+Nazarbayev+Airport"
    },
    {
        iata: "NRT",
        city: "Tokyo",
        country: "Japan",
        terminal: "Terminal 2",
        timezone: "Asia/Tokyo",
        distanceCenter: "60 km to Center",
        nearbyAirports: "HND: 60km",
        phone: "+81 476 34 8000",
        website: "https://www.narita-airport.jp",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Narita+Airport"
    },
    {
        iata: "NUM",
        city: "Neom",
        country: "Saudi Arabia",
        terminal: "Neom Bay",
        timezone: "Asia/Riyadh",
        distanceCenter: "New Development",
        nearbyAirports: "TUU: 150km",
        phone: "+966 14 420 0000",
        website: "https://www.neom.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Neom+Bay+Airport"
    },
    {
        iata: "OLB",
        city: "Olbia",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "4 km to Center",
        nearbyAirports: "None",
        phone: "+39 0789 563 444",
        website: "https://www.geasar.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Olbia+Airport"
    },
    {
        iata: "OSL",
        city: "Oslo",
        country: "Norway",
        terminal: "Main Terminal",
        timezone: "Europe/Oslo",
        distanceCenter: "50 km to Center",
        nearbyAirports: "TRF: 120km",
        phone: "+47 64 81 20 00",
        website: "https://avinor.no/en/airport/oslo-airport/",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Oslo+Airport"
    },
    {
        iata: "OTP",
        city: "Bucharest",
        country: "Romania",
        terminal: "Departures",
        timezone: "Europe/Bucharest",
        distanceCenter: "17 km to Center",
        nearbyAirports: "BBU: 8km",
        phone: "+40 21 204 1000",
        website: "https://www.bucharestairports.ro",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Henri+Coanda+Airport"
    },
    {
        iata: "OVB",
        city: "Novosibirsk",
        country: "Russia",
        terminal: "Terminal B",
        timezone: "Asia/Novosibirsk",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+7 383 216 99 99",
        website: "https://tolmachevo.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tolmachevo+Airport"
    },
    {
        iata: "PEK",
        city: "Beijing",
        country: "China",
        terminal: "Terminal 3",
        timezone: "Asia/Shanghai",
        distanceCenter: "30 km to Center",
        nearbyAirports: "PKX: 50km",
        phone: "+86 10 96158",
        website: "https://www.bcia.com.cn",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Beijing+Capital+Airport"
    },
    {
        iata: "PEN",
        city: "Penang",
        country: "Malaysia",
        terminal: "Main Terminal",
        timezone: "Asia/Kuala_Lumpur",
        distanceCenter: "16 km to Center",
        nearbyAirports: "LGK: 120km",
        phone: "+60 4 643 4411",
        website: "https://www.penangairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Penang+Airport"
    },
    {
        iata: "PER",
        city: "Perth",
        country: "Australia",
        terminal: "Terminal 1",
        timezone: "Australia/Perth",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+61 8 9478 8888",
        website: "https://www.perthairport.com.au",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Perth+Airport"
    },
    {
        iata: "PEW",
        city: "Peshawar",
        country: "Pakistan",
        terminal: "International",
        timezone: "Asia/Karachi",
        distanceCenter: "5 km to Center",
        nearbyAirports: "ISB: 180km",
        phone: "+92 91 921 1525",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Peshawar+Airport"
    },
    {
        iata: "PHL",
        city: "Philadelphia",
        country: "USA",
        terminal: "Terminal A-West",
        timezone: "America/New_York",
        distanceCenter: "15 km to Center",
        nearbyAirports: "EWR: 130km",
        phone: "+1 215 937 6937",
        website: "https://www.phl.org",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Philadelphia+Airport"
    },
    {
        iata: "PMO",
        city: "Palermo",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "35 km to Center",
        nearbyAirports: "CTA: 240km",
        phone: "+39 091 702 0111",
        website: "https://www.aeroportodipalermo.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Palermo+Airport"
    },
    {
        iata: "POZ",
        city: "Poznan",
        country: "Poland",
        terminal: "Main Terminal",
        timezone: "Europe/Warsaw",
        distanceCenter: "7 km to Center",
        nearbyAirports: "None",
        phone: "+48 61 849 23 43",
        website: "https://www.poznan-airport.com.pl",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Poznan+Airport"
    },
    {
        iata: "PRG",
        city: "Prague",
        country: "Czech Republic",
        terminal: "Terminal 1",
        timezone: "Europe/Prague",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+420 220 111 888",
        website: "https://www.prg.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Prague+Airport"
    },
    {
        iata: "PSA",
        city: "Pisa",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "2 km to Center",
        nearbyAirports: "FLR: 80km",
        phone: "+39 050 849 111",
        website: "https://www.pisa-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Pisa+Airport"
    },
    {
        iata: "RSI",
        city: "Red Sea",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "Resort Area",
        nearbyAirports: "YNB: 150km",
        phone: "+966 14 420 1111",
        website: "https://www.redseaglobal.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Red+Sea+International+Airport"
    },
    {
        iata: "RUH",
        city: "Riyadh",
        country: "Saudi Arabia",
        terminal: "Terminal 2",
        timezone: "Asia/Riyadh",
        distanceCenter: "35 km to Center",
        nearbyAirports: "None",
        phone: "+966 9200 20090",
        website: "https://kkia.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=King+Khalid+International+Airport"
    },
    {
        iata: "SAW",
        city: "Istanbul",
        country: "Turkey",
        terminal: "Sabiha Gokcen",
        timezone: "Europe/Istanbul",
        distanceCenter: "40 km to Kadikoy",
        nearbyAirports: "IST: 85km",
        phone: "+90 216 588 88 88",
        website: "https://www.sabihagokcen.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sabiha+Gokcen+Airport"
    },
    {
        iata: "SEA",
        city: "Seattle",
        country: "USA",
        terminal: "South Satellite",
        timezone: "America/Los_Angeles",
        distanceCenter: "20 km to Center",
        nearbyAirports: "BFI: 10km",
        phone: "+1 206 787 5388",
        website: "https://www.portseattle.org",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Seattle+Tacoma+Airport"
    },
    {
        iata: "SEZ",
        city: "Seychelles",
        country: "Seychelles",
        terminal: "International",
        timezone: "Indian/Mahe",
        distanceCenter: "10 km to Victoria",
        nearbyAirports: "None",
        phone: "+248 438 4000",
        website: "https://seychellesairports.sc",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Seychelles+International+Airport"
    },
    {
        iata: "SFO",
        city: "San Francisco",
        country: "USA",
        terminal: "International A",
        timezone: "America/Los_Angeles",
        distanceCenter: "20 km to Center",
        nearbyAirports: "OAK: 30km",
        phone: "+1 650 821 8211",
        website: "https://www.flysfo.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=San+Francisco+Airport"
    },
    {
        iata: "SGN",
        city: "Ho Chi Minh City",
        country: "Vietnam",
        terminal: "Terminal 2",
        timezone: "Asia/Bangkok",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+84 28 3848 5383",
        website: "http://tansonnhatairport.vn",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tan+Son+Nhat+Airport"
    },
    {
        iata: "SIN",
        city: "Singapore",
        country: "Singapore",
        terminal: "Terminal 1",
        timezone: "Asia/Singapore",
        distanceCenter: "20 km to Center",
        nearbyAirports: "XSP: 15km",
        phone: "+65 6595 6868",
        website: "https://www.changiairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Changi+Airport"
    },
    {
        iata: "SJJ",
        city: "Sarajevo",
        country: "Bosnia",
        terminal: "Main Terminal",
        timezone: "Europe/Sarajevo",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+387 33 289 100",
        website: "https://www.sarajevo-airport.ba",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sarajevo+Airport"
    },
    {
        iata: "SKD",
        city: "Samarkand",
        country: "Uzbekistan",
        terminal: "New Terminal",
        timezone: "Asia/Samarkand",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+998 66 230 86 41",
        website: "https://www.ssl.uz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Samarkand+Airport"
    },
    {
        iata: "SKT",
        city: "Sialkot",
        country: "Pakistan",
        terminal: "International",
        timezone: "Asia/Karachi",
        distanceCenter: "20 km to Center",
        nearbyAirports: "LHE: 130km",
        phone: "+92 52 111 742 575",
        website: "https://www.sialkotairport.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sialkot+Airport"
    },
    {
        iata: "SLL",
        city: "Salalah",
        country: "Oman",
        terminal: "New Terminal",
        timezone: "Asia/Muscat",
        distanceCenter: "5 km to Center",
        nearbyAirports: "None",
        phone: "+968 23 368 002",
        website: "https://salalahairport.co.om",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Salalah+Airport"
    },
    {
        iata: "SOF",
        city: "Sofia",
        country: "Bulgaria",
        terminal: "Terminal 2",
        timezone: "Europe/Sofia",
        distanceCenter: "10 km to Center",
        nearbyAirports: "None",
        phone: "+359 2 937 2211",
        website: "https://sofia-airport.eu",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sofia+Airport"
    },
    {
        iata: "SPX",
        city: "Giza / Cairo",
        country: "Egypt",
        terminal: "Main Terminal",
        timezone: "Africa/Cairo",
        distanceCenter: "45 km to Downtown",
        nearbyAirports: "CAI: 65km",
        phone: "+20 2 3344 5555",
        website: "http://www.civilaviation.gov.eg",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sphinx+International+Airport"
    },
    {
        iata: "STN",
        city: "London Stansted",
        country: "UK",
        terminal: "Main Terminal",
        timezone: "Europe/London",
        distanceCenter: "60 km to London",
        nearbyAirports: "LHR: 90km",
        phone: "+44 844 335 1803",
        website: "https://www.stanstedairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Stansted+Airport"
    },
    {
        iata: "SVX",
        city: "Yekaterinburg",
        country: "Russia",
        terminal: "Terminal B",
        timezone: "Asia/Yekaterinburg",
        distanceCenter: "16 km to Center",
        nearbyAirports: "None",
        phone: "+7 343 226 85 82",
        website: "https://svx.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Koltsovo+Airport"
    },
    {
        iata: "SYD",
        city: "Sydney",
        country: "Australia",
        terminal: "Terminal 1",
        timezone: "Australia/Sydney",
        distanceCenter: "8 km to Center",
        nearbyAirports: "None",
        phone: "+61 2 9667 9111",
        website: "https://www.sydneyairport.com.au",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Sydney+Airport"
    },
    {
        iata: "SYZ",
        city: "Shiraz",
        country: "Iran",
        terminal: "International",
        timezone: "Asia/Tehran",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+98 71 3323 1800",
        website: "https://shiraz.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Shiraz+Airport"
    },
    {
        iata: "SZG",
        city: "Salzburg",
        country: "Austria",
        terminal: "Terminal 1",
        timezone: "Europe/Vienna",
        distanceCenter: "4 km to Center",
        nearbyAirports: "MUC: 180km",
        phone: "+43 662 8580 0",
        website: "https://www.salzburg-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Salzburg+Airport"
    },
    {
        iata: "TAS",
        city: "Tashkent",
        country: "Uzbekistan",
        terminal: "Terminal 2",
        timezone: "Asia/Tashkent",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+998 78 140 28 01",
        website: "https://tashkent-airport.uz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tashkent+Airport"
    },
    {
        iata: "TBS",
        city: "Tbilisi",
        country: "Georgia",
        terminal: "Main Terminal",
        timezone: "Asia/Tbilisi",
        distanceCenter: "17 km to Center",
        nearbyAirports: "None",
        phone: "+995 32 231 04 21",
        website: "https://www.tbilisiairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tbilisi+Airport"
    },
    {
        iata: "THR",
        city: "Tehran",
        country: "Iran",
        terminal: "Mehrabad",
        timezone: "Asia/Tehran",
        distanceCenter: "5 km to Center",
        nearbyAirports: "IKA (Intl)",
        phone: "+98 21 61021",
        website: "https://mehrabad.airport.ir",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Mehrabad+Airport"
    },
    {
        iata: "TIF",
        city: "Taif",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "30 km to Center",
        nearbyAirports: "None",
        phone: "+966 2 736 7777",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Taif+Airport"
    },
    {
        iata: "TIV",
        city: "Tivat",
        country: "Montenegro",
        terminal: "Terminal 1",
        timezone: "Europe/Podgorica",
        distanceCenter: "4 km to Center",
        nearbyAirports: "DBV: 50km",
        phone: "+382 32 671 337",
        website: "https://montenegroairports.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tivat+Airport"
    },
    {
        iata: "TLV",
        city: "Tel Aviv",
        country: "Israel",
        terminal: "Terminal 3",
        timezone: "Asia/Jerusalem",
        distanceCenter: "20 km to Center",
        nearbyAirports: "None",
        phone: "+972 3 978 3333",
        website: "https://www.iaa.gov.il",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ben+Gurion+Airport"
    },
    {
        iata: "TPE",
        city: "Taipei",
        country: "Taiwan",
        terminal: "Terminal 2",
        timezone: "Asia/Taipei",
        distanceCenter: "40 km to Center",
        nearbyAirports: "TSA: 5km",
        phone: "+886 3 398 3728",
        website: "https://www.taoyuan-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Taoyuan+Airport"
    },
    {
        iata: "TRV",
        city: "Thiruvananthapuram",
        country: "India",
        terminal: "Terminal 2",
        timezone: "Asia/Kolkata",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+91 471 270 2600",
        website: "https://www.aai.aero",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Trivandrum+Airport"
    },
    {
        iata: "TUN",
        city: "Tunis",
        country: "Tunisia",
        terminal: "Main Terminal",
        timezone: "Africa/Tunis",
        distanceCenter: "7 km to Center",
        nearbyAirports: "None",
        phone: "+216 71 754 000",
        website: "https://www.tunis-carthage-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tunis+Carthage+Airport"
    },
    {
        iata: "TUU",
        city: "Tabuk",
        country: "Saudi Arabia",
        terminal: "International",
        timezone: "Asia/Riyadh",
        distanceCenter: "5 km to Center",
        nearbyAirports: "None",
        phone: "+966 4 422 2300",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Tabuk+Airport"
    },
    {
        iata: "TZX",
        city: "Trabzon",
        country: "Turkey",
        terminal: "Main Terminal",
        timezone: "Europe/Istanbul",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+90 462 328 09 40",
        website: "https://trabzon.dhmi.gov.tr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Trabzon+Airport"
    },
    {
        iata: "UET",
        city: "Quetta",
        country: "Pakistan",
        terminal: "Main Terminal",
        timezone: "Asia/Karachi",
        distanceCenter: "12 km to Center",
        nearbyAirports: "None",
        phone: "+92 81 924 1002",
        website: "http://caapakistan.com.pk",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Quetta+Airport"
    },
    {
        iata: "UFA",
        city: "Ufa",
        country: "Russia",
        terminal: "Terminal 1",
        timezone: "Asia/Yekaterinburg",
        distanceCenter: "25 km to Center",
        nearbyAirports: "None",
        phone: "+7 347 229 52 95",
        website: "https://www.airportufa.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Ufa+Airport"
    },
    {
        iata: "UTP",
        city: "Pattaya",
        country: "Thailand",
        terminal: "U-Tapao Intl",
        timezone: "Asia/Bangkok",
        distanceCenter: "40 km to Pattaya Beach",
        nearbyAirports: "BKK: 140km",
        phone: "+66 38 245 595",
        website: "http://www.utapao.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=U-Tapao+Airport"
    },
    {
        iata: "VCE",
        city: "Venice",
        country: "Italy",
        terminal: "Main Terminal",
        timezone: "Europe/Rome",
        distanceCenter: "13 km to Center",
        nearbyAirports: "TSF: 40km",
        phone: "+39 041 260 9260",
        website: "https://www.veneziaairport.it",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Venice+Marco+Polo+Airport"
    },
    {
        iata: "VIE",
        city: "Vienna",
        country: "Austria",
        terminal: "Terminal 3",
        timezone: "Europe/Vienna",
        distanceCenter: "18 km to Center",
        nearbyAirports: "BTS: 60km",
        phone: "+43 1 70070",
        website: "https://www.viennaairport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Vienna+Airport"
    },
    {
        iata: "VKO",
        city: "Moscow",
        country: "Russia",
        terminal: "Terminal A",
        timezone: "Europe/Moscow",
        distanceCenter: "28 km to Center",
        nearbyAirports: "SVO: 50km | DME: 60km",
        phone: "+7 495 937 55 55",
        website: "http://vnukovo.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Vnukovo+Airport"
    },
    {
        iata: "VNO",
        city: "Vilnius",
        country: "Lithuania",
        terminal: "Main Terminal",
        timezone: "Europe/Vilnius",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+370 612 44442",
        website: "https://www.vilnius-airport.lt",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Vilnius+Airport"
    },
    {
        iata: "VOG",
        city: "Volgograd",
        country: "Russia",
        terminal: "Terminal C",
        timezone: "Europe/Volgograd",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+7 8442 26 10 87",
        website: "https://mav.ru",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Volgograd+Airport"
    },
    {
        iata: "WAW",
        city: "Warsaw",
        country: "Poland",
        terminal: "Terminal A",
        timezone: "Europe/Warsaw",
        distanceCenter: "10 km to Center",
        nearbyAirports: "WMI: 40km",
        phone: "+48 22 650 42 20",
        website: "https://www.lotnisko-chopina.pl",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Warsaw+Chopin+Airport"
    },
    {
        iata: "YNB",
        city: "Yanbu",
        country: "Saudi Arabia",
        terminal: "Main Terminal",
        timezone: "Asia/Riyadh",
        distanceCenter: "6 km to Center",
        nearbyAirports: "None",
        phone: "+966 4 390 0000",
        website: "https://gaca.gov.sa",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Yanbu+Airport"
    },
    {
        iata: "YYZ",
        city: "Toronto",
        country: "Canada",
        terminal: "Terminal 1",
        timezone: "America/Toronto",
        distanceCenter: "25 km to Center",
        nearbyAirports: "YTZ: 25km",
        phone: "+1 416 247 7678",
        website: "https://www.torontopearson.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Toronto+Pearson+Airport"
    },
    {
        iata: "ZAG",
        city: "Zagreb",
        country: "Croatia",
        terminal: "Main Terminal",
        timezone: "Europe/Zagreb",
        distanceCenter: "15 km to Center",
        nearbyAirports: "None",
        phone: "+385 1 4562 170",
        website: "https://www.zagreb-airport.hr",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Zagreb+Airport"
    },
    {
        iata: "ZNZ",
        city: "Zanzibar",
        country: "Tanzania",
        terminal: "Terminal 3",
        timezone: "Africa/Dar_es_Salaam",
        distanceCenter: "7 km to Stone Town",
        nearbyAirports: "DAR: Ferry/Flight",
        phone: "+255 24 223 3979",
        website: "https://www.zaa.go.tz",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Zanzibar+Airport"
    },
    {
        iata: "ZRH",
        city: "Zurich",
        country: "Switzerland",
        terminal: "Terminal 2",
        timezone: "Europe/Zurich",
        distanceCenter: "13 km to Center",
        nearbyAirports: "BSL: 80km",
        phone: "+41 43 816 22 11",
        website: "https://www.zurich-airport.com",
        locationUrl: "https://www.google.com/maps/search/?api=1&query=Zurich+Airport"
    }
];
